### ISSUE TITLE
validate_inclusion_of: in_array does not accept a Relation

### ISSUE THREAD

**Issue by Looooong** [thoughtbot/shoulda-matchers#1011]
I have the following models

```rails
class Quiz
  belongs_to :solution, class_name: 'Answer'
  has_many :answers

  validates :solution, inclusion: { in: lambda(&:answers) }
end

class Answer
  belongs_to :quiz
end
```

When I test

```rails
RSpec.describe Quiz, type: :model do
  it { is_expected.to validate_inclusion_of(:solution).in_array(subject.answers) }
end
```

It raises error:

```
Failure/Error: it { is_expected.to validate_inclusion_of(:solution).in_array(subject.answers.to_a) }
     
     ActiveRecord::AssociationTypeMismatch:
       Answer(#47315402670680) expected, got String(#47315336560740)
     # /var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/associations/association.rb:218:in `raise_on_type_mismatch!'
     # /var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/associations/belongs_to_association.rb:12:in `replace'
     # /var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/associations/singular_association.rb:17:in `writer'
     # /var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/associations/builder/association.rb:123:in `solution='
     # /var/lib/gems/2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setter.rb:83:in `public_send'
     # /var/lib/gems/2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setter.rb:83:in `set'
     # /var/lib/gems/2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setter.rb:67:in `set!'
     # /var/lib/gems/2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:38:in `matches?'
     # /var/lib/gems/2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:42:in `does_not_match?'
     # /var/lib/gems/2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:28:in `each'
     # /var/lib/gems/2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:28:in `detect'
     # /var/lib/gems/2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:28:in `first_failing'
     # /var/lib/gems/2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher.rb:533:in `public_send'
     # /var/lib/gems/2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher.rb:533:in `run'
     # /var/lib/gems/2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher.rb:394:in `matches?'
     # /var/lib/gems/2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validation_matcher.rb:155:in `run_allow_or_disallow_matcher'
     # /var/lib/gems/2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validation_matcher.rb:88:in `allows_value_of'
     # /var/lib/gems/2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:470:in `block in disallows_value_outside_of_array?'
     # /var/lib/gems/2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:469:in `any?'
     # /var/lib/gems/2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:469:in `disallows_value_outside_of_array?'
     # /var/lib/gems/2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:405:in `matches_for_array?'
     # /var/lib/gems/2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:383:in `matches?'
     # ./spec/models/quiz_spec.rb:18:in `block (2 levels) in <top (required)>'
```

It looks like Should Matcher is assigning `String` to `quiz.solution` which is an association.

**Comment by Looooong** [comment]
I can write something like

```rails
validates :solution_id, inclusion: { in: lambda(&:answer_ids) }

# Then test
it { is_expected.to validate_inclusion_of(:solution_id).in_array(subject.answer_ids) }
```

However, this wouldn't validate correctly upon object creation

```rails
quiz = Quiz.new
quiz.answers.build([...])

quiz.solution = quiz.answers[0]
quiz.valid? # true

quiz.solution = Answer.new
quiz.valid? # true
```

**Comment by wlffann** [comment]
I can confirm this bug. 

```ruby
class Game < ApplicationRecord
  belongs_to :player, class_name: 'User'

  validates :player, inclusion: { in: lambda(&:users) }
end

class User < ApplicationRecord
  has_many :games
end
```

```ruby
it { is_expected.to validate_inclusion_of(:player).in_array(User.all)}
```

Returns 
```
     Failure/Error: it { is_expected.to validate_inclusion_of(:player).in_array(User.all)}

     ActiveRecord::AssociationTypeMismatch:
       User(#70211158900900) expected, got String(#70211131056240)
     # /Users/anniewolff/.rvm/gems/ruby-2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setter.rb:83:in `public_send'
     # /Users/anniewolff/.rvm/gems/ruby-2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setter.rb:83:in `set'
     # /Users/anniewolff/.rvm/gems/ruby-2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setter.rb:67:in `set!'
     # /Users/anniewolff/.rvm/gems/ruby-2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:38:in `matches?'
     # /Users/anniewolff/.rvm/gems/ruby-2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:42:in `does_not_match?'
     # /Users/anniewolff/.rvm/gems/ruby-2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:28:in `each'
     # /Users/anniewolff/.rvm/gems/ruby-2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:28:in `detect'
     # /Users/anniewolff/.rvm/gems/ruby-2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:28:in `first_failing'
     # /Users/anniewolff/.rvm/gems/ruby-2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher.rb:533:in `public_send'
     # /Users/anniewolff/.rvm/gems/ruby-2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher.rb:533:in `run'
     # /Users/anniewolff/.rvm/gems/ruby-2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher.rb:394:in `matches?'
     # /Users/anniewolff/.rvm/gems/ruby-2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validation_matcher.rb:155:in `run_allow_or_disallow_matcher'
     # /Users/anniewolff/.rvm/gems/ruby-2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validation_matcher.rb:88:in `allows_value_of'
     # /Users/anniewolff/.rvm/gems/ruby-2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:470:in `block in disallows_value_outside_of_array?'
     # /Users/anniewolff/.rvm/gems/ruby-2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:469:in `any?'
     # /Users/anniewolff/.rvm/gems/ruby-2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:469:in `disallows_value_outside_of_array?'
     # /Users/anniewolff/.rvm/gems/ruby-2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:405:in `matches_for_array?'
     # /Users/anniewolff/.rvm/gems/ruby-2.3.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:383:in `matches?'
     # ./spec/models/game_spec.rb:5:in `block (3 levels) in <top (required)>'
```

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
