### ISSUE TITLE
validate_length_of fails for PG array column

### ISSUE THREAD

**Issue by gonzalobustos** [thoughtbot/shoulda-matchers#1064]
Hi all,

I am experiencing the following when testing a PG array field with rails 5.1.3 and shoulda-matchers 3.1.2

Migration
`t.text :other_names, array: true, default: []
`

Model
```
class Specie < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }, uniqueness: true
  validates :other_names, length: { maximum: 200 }, allow_nil: true
```

Spec
```
  it { should validate_length_of(:name).is_at_most(50) }
  it { should validate_length_of(:other_names).is_at_most(200) }
```

bundle exec rspec output

```
Failures:

  1) Specie should validate that the length of :other_names is at most 200
     Failure/Error: it { should validate_length_of(:other_names).is_at_most(200) }
     
       Specie did not properly validate that the length of :other_names is at
       most 200.
         After setting :other_names to
         
     
         As indicated in the message above, :other_names seems to be changing
         certain values as they are set, and this could have something to do
         with why this test is failing. If you've overridden the writer method
         for this attribute, then you may need to change it to make this test
         pass, or do something else entirely.
     # ./spec/models/specie_spec.rb:13:in `block (2 levels) in <top (required)>'
     # ./spec/support/database_cleaner.rb:7:in `block (3 levels) in <top (required)>'
     # /usr/local/bundle/gems/database_cleaner-1.6.2/lib/database_cleaner/generic/base.rb:16:in `cleaning'
     # /usr/local/bundle/gems/database_cleaner-1.6.2/lib/database_cleaner/base.rb:98:in `cleaning'
     # /usr/local/bundle/gems/database_cleaner-1.6.2/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # /usr/local/bundle/gems/database_cleaner-1.6.2/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/support/database_cleaner.rb:7:in `block (2 levels) in <top (required)>'

Finished in 0.55964 seconds (files took 2.24 seconds to load)
22 examples, 1 failure, 14 pending

Failed examples:

rspec ./spec/models/specie_spec.rb:13 # Specie should validate that the length of :other_names is at most 200
```

**Comment by mcmire** [comment]
The error message you're getting is admittedly a little weird, however, `validate_length_of` matcher is designed to only work with string columns -- we don't support array columns. We would definitely appreciate a PR if this is something you would like.

In the meantime you can simulate this with `allow_value`:

``` ruby
it { should allow_value(Array.new(200, "x")).for(:other_values) }
it { should_not allow_value(Array.new(201, "x")).for(:other_values).with_message("is too long") }
```

**Comment by gonzalobustos** [comment]
Okay, I got it.
Thanks for sharing an alternative. I am closing this for now.
