### ISSUE TITLE
undefined method `_process_action_callbacks' for NilClass:Class

### ISSUE THREAD

**Issue by khiav223577** [thoughtbot/shoulda-matchers#1099]
`shoulda-matchers` (latest version 3.1.1) doesn't work in the following example:

### Example
```rb
RSpec.describe UserController, type: :controller do
  subject(:response_body){ JSON.parse(response.body) }

  describe 'GET index' do
    before{ get :index }
    it{ should use_before_action(:user_auth)}
    it{ expect(response_body['data']).to be_present }
  end
end
```

### Error Messages
```
NoMethodError:
       undefined method `_process_action_callbacks' for NilClass:Class
     # /Users/khiav223577/.rvm/gems/ruby-2.3.3/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/action_controller/callback_matcher.rb:184:in `callbacks'
     # ./spec/support/shoulda/matchers/action_controller/callback_matcher.rb:78:in `filter_matches?'
     # ./spec/support/shoulda/matchers/action_controller/callback_matcher.rb:58:in `matches?'
     # ./spec/controllers/user_controller_spec.rb:123:in `block (4 levels) in <top (required)>'
```

I find a workaround by using `let` instead of `subject` or adding `subject{ described_class.new }` below other subjects, but I think this doesn't solve the real problem.

**Comment by mcmire** [comment]
The controller matchers work best when your subject is a controller instance. By default, this is the case, and I would advise against changing the subject. But if you really, really want to do that, then write your test this way:

```
it { expect(controller).to use_before_action(:user_auth) }
```
