### ISSUE TITLE
undefined method `reflect_on_association' for Class:Class

### ISSUE THREAD

**Issue by ahmgeek** [thoughtbot/shoulda-matchers#1104]
```
# models/album.rb
class Album < ApplicationRecord
  belongs_to :user
```

```
RSpec.describe Album, type: :model do
  subject { described_class }

  it { should belong_to(:user) }
```

```
     NoMethodError:
       undefined method `reflect_on_association' for Class:Class
     # /Users/aht/.rvm/gems/ruby-2.5.0@eschools/gems/shoulda-matchers-3.1.2/lib/shoulda/matchers/active_record/association_matchers/model_reflector.rb:21:in `reflect_on_association'
     # /Users/aht/.rvm/gems/ruby-2.5.0@eschools/gems/shoulda-matchers-3.1.2/lib/shoulda/matchers/active_record/association_matchers/model_reflector.rb:17:in `reflection'
     # /Users/aht/.rvm/gems/ruby-2.5.0@eschools/gems/shoulda-matchers-3.1.2/lib/shoulda/matchers/active_record/association_matcher.rb:883:in `reflection'
     # /Users/aht/.rvm/gems/ruby-2.5.0@eschools/gems/shoulda-matchers-3.1.2/lib/shoulda/matchers/active_record/association_matcher.rb:1060:in `association_exists?'
     # /Users/aht/.rvm/gems/ruby-2.5.0@eschools/gems/shoulda-matchers-3.1.2/lib/shoulda/matchers/active_record/association_matcher.rb:989:in `matches?'
     # ./spec/models/album_spec.rb:7:in `block (2 levels) in <top (required)>'
```

`Rails 5.1.6`
`shoulda-matchers (3.1.2)`

**Comment by mcmire** [comment]
No problem!
