### ISSUE TITLE
NoMethodError allow_nil for validate_length_of

### ISSUE THREAD

**Issue by aaronmallen** [thoughtbot/shoulda-matchers#1147]
I am receiving the following error:

```bash
Failures:

  1) Account::Owner
     Failure/Error: it { should validate_length_of(:password).allow_nil.is_at_least(8).is_at_most(72) }

     NoMethodError:
       undefined method `allow_nil' for #<Shoulda::Matchers::ActiveModel::ValidateLengthOfMatcher:0x00007fb0b39e7a80>
       Did you mean?  allows_value_of
     # ./spec/models/account/owner_spec.rb:45:in `block (2 levels) in <top (required)>'
     # ./spec/support/database_cleaner.rb:12:in `block (3 levels) in <top (required)>'
     # ~/.rvm/gems/ruby-2.5.1@my_project/gems/database_cleaner-1.7.0/lib/database_cleaner/generic/base.rb:16:in `cleaning'
     # ~/.rvm/gems/ruby-2.5.1@my_project/gems/database_cleaner-1.7.0/lib/database_cleaner/base.rb:100:in `cleaning'
     # ~/.rvm/gems/ruby-2.5.1@my_project/gems/database_cleaner-1.7.0/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # ~/.rvm/gems/ruby-2.5.1@my_project/gems/database_cleaner-1.7.0/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/support/database_cleaner.rb:11:in `block (2 levels) in <top (required)>'
```

I am testing the following validation on a model having `has_secure_password validations: false`:

```ruby
validates :password, presence: { if: :admin? },
                     length: { allow_nil: true, minimum: 8, maximum: 72 }, 
                     confirmation: { allow_blank: true }
```

The following spec produces the failure:

```ruby
it { should validate_length_of(:password).is_at_least(8).is_at_most(72).allow_nil }
```

```
shoulda-matchers (3.1.2)
rspec-core (3.8.0)
rails (5.2.1)
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
```

**Comment by aaronmallen** [comment]
this is documented as being supported here: https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/active_model/validate_length_of_matcher.rb#L219

**Comment by guialbuk** [comment]
Hi @aaronmallen 

You are using version `3.1.2` but you're reading the documentation from the `master` branch for version `4.0.0.rc1` 🙂

**Comment by aaronmallen** [comment]
@guialbuk confirmed upgrading to `4.0.0.rc1` fixes the issue. TYVM
