### ISSUE TITLE
config 'with.library :action_controller' not working with non rails app

### ISSUE THREAD

**Issue by sandradc** [thoughtbot/shoulda-matchers#1202]
Hello!
I am working on a _Ruby on Jets_ app and using the **shoulda_matchers** gem, no problem to test my models and active_records but a problem occurs when I try to test my controllers. 

Here is my config:

```
require 'shoulda-matchers'

Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    with.test_framework :rspec
    with.library :active_record
    with.library :active_model
    with.library :action_controller # adding this line creates an error
  end
end
```

and here is the test I try to run:
```
require 'spec_helper'

RSpec.describe UsersController, type: :controller do
  describe 'Users controller specs' do
    context 'when POST #create' do
      it 'creates a new user' do
        params = {
          first_name: 'some first_name',
          last_name: 'some last_name',
          email: 'some_address@mail.com',
          password: 'password123'
        }
        expect { post :create, params: { user: params } }.to change(User, :count).by(1)
      end
    end
  end
end
```

So if I add this line `with.library :action_controller` in my config, I have the following error when I run `bundle exec rspec` -> 
```
NoMethodError:
       undefined method `end_with?' for :create:Symbol
```

I guess the problem is that it is not yet possible to use the action_controller lib with a non rails app. Is there any way to improve it? 

Thanks a lot in advance

**Comment by mcmire** [comment]
@sandradc I'm not certain where that is coming from. Can you post the backtrace?

**Comment by sandradc** [comment]
@mcmire sure, here it is
```
     # /Users/sandra/.rvm/gems/ruby-2.5.3/gems/jets-1.8.9/lib/jets/spec_helpers/request.rb:82:in `find_route!'
     # /Users/sandra/.rvm/gems/ruby-2.5.3/gems/jets-1.8.9/lib/jets/spec_helpers/request.rb:92:in `dispatch!'
     # /Users/sandra/.rvm/gems/ruby-2.5.3/gems/jets-1.8.9/lib/jets/spec_helpers.rb:42:in `http_call'
     # /Users/sandra/.rvm/gems/ruby-2.5.3/gems/jets-1.8.9/lib/jets/spec_helpers.rb:21:in `block (2 levels) in <module:SpecHelpers>'
     # ./spec/controllers/users_controller_spec.rb:14:in `block (4 levels) in <top (required)>'
     # ./spec/controllers/users_controller_spec.rb:14:in `block (3 levels) in <top (required)>'
```

**Comment by mcmire** [comment]
After looking at the Ruby on Jets library, specifically the `spec_helpers.rb` file referred to in the backtrace, it looks like it doesn't support the same syntax that Rails supports when it comes to executing actions in controller tests. In fact it seems like its controller tests are more like request specs. So instead of saying this:

``` ruby
post :create, params: { user: params }
```

you say:

``` ruby
post "/", params: { user: params }    # or whatever the path here is supposed to be
``

Since they're request specs, you might want to use `type: :request` to tag the example group (and/or place your tests under `spec/requests`). Also, I don't know if you'd be able to use the ActionController matchers in this context, since they rely on access to some kind of controller instance, and that doesn't seem to be how Jets works. What matchers are you specifically wanting to use?

**Comment by sandradc** [comment]
@mcmire thanks for the advise! I have followed what you said and here is my test updated:
```
require 'spec_helper'

RSpec.describe 'Users', type: :request do
  describe 'POST /users' do
    it 'creates user' do
      post '/users', params: { user: attributes_for(:user) }
      expect(response).to have_http_status(:created)
      expect(response).to change(User, :count).by(1)
    end
  end
end
```

I know use factory_bot with the following factory file:
```
FactoryBot.define do
  factory :user do
    first_name { 'Janet' }
    last_name { 'Bobby' }
    email { Faker::Internet.email }
    password { 'user123' }
  end
end
```

But now it raises another error when I run `bundle exec rspec`:
```
Failure/Error:
       params.require(:user).permit(
         :first_name,
         :last_name,
         :email,
         :password
       )

     NoMethodError:
       undefined method `permit' for #<String:0x00007fb2985fcab0>
```

with the following backtrace:
```
 # ./app/controllers/users_controller.rb:17:in `user_params'
 # ./app/controllers/users_controller.rb:5:in `create'
 # /Users/sandra/.rvm/gems/ruby-2.5.3/gems/jets-1.8.9/lib/jets/controller/base.rb:43:in `dispatch!'
 # /Users/sandra/.rvm/gems/ruby-2.5.3/gems/jets-1.8.9/lib/jets/spec_helpers/request.rb:94:in `dispatch!'
 # /Users/sandra/.rvm/gems/ruby-2.5.3/gems/jets-1.8.9/lib/jets/spec_helpers.rb:42:in `http_call'
 # /Users/sandra/.rvm/gems/ruby-2.5.3/gems/jets-1.8.9/lib/jets/spec_helpers.rb:21:in `block (2 levels) in <module:SpecHelpers>'
 # ./spec/requests/users_controller_spec.rb:8:in `block (3 levels) in <top (required)>'
```

Backtrace is mostly related to this file: https://github.com/tongueroo/jets/blob/master/lib/jets/spec_helpers.rb

I don't quite get what is the matter here. Could you help me understand? Thanks in advance.

**Comment by mcmire** [comment]
I'm not sure. What is `params` in this case? What is `params.require(:user)`?

**Comment by mcmire** [comment]
Hey — I'm going to close this issue as it doesn't seem to be a shoulda-matchers issue, but let me know if you need any more help with this.
