### ISSUE TITLE
validate_presence_of(:active_storage_field) throws exception

### ISSUE THREAD

**Issue by gmmcal** [thoughtbot/shoulda-matchers#1223]
Gem version: `4.1.0`
Ruby version: `2.6.3`
Rails version: `6.0.0.rc1`
Rspec version: `3.8.1`

Given a model

```
class Test < ApplicationRecord
  has_one_attached :file
end
```

and a test

```
RSpec.describe Test, type: :model do
  it { is_expected.to validate_presence_of(:file) }
end
```

the test fails with this exception

```
1) Test should validate that :file cannot be empty/falsy
    Failure/Error: it { is_expected.to validate_presence_of(:file) }
    
    ActiveSupport::MessageVerifier::InvalidSignature:
        ActiveSupport::MessageVerifier::InvalidSignature
    # <gems_path>/gems/activestorage-6.0.0.rc1/app/models/active_storage/blob.rb:49:in `find_signed'
    # <gems_path>/gems/activestorage-6.0.0.rc1/lib/active_storage/attached/changes/create_one.rb:63:in `find_or_build_blob'
    # <gems_path>/gems/activestorage-6.0.0.rc1/lib/active_storage/attached/changes/create_one.rb:19:in `blob'
    # <gems_path>/gems/activestorage-6.0.0.rc1/lib/active_storage/attached/changes/create_one.rb:42:in `find_attachment'
    # <gems_path>/gems/activestorage-6.0.0.rc1/lib/active_storage/attached/changes/create_one.rb:38:in `find_or_build_attachment'
    # <gems_path>/gems/activestorage-6.0.0.rc1/lib/active_storage/attached/changes/create_one.rb:15:in `attachment'
    # <gems_path>/gems/activestorage-6.0.0.rc1/lib/active_storage/attached/one.rb:13:in `attachment'
    # <gems_path>/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setter.rb:140:in `attribute_changed_value?'
    # <gems_path>/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setter.rb:166:in `raise_attribute_changed_value_error?'
    # <gems_path>/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setter.rb:88:in `set'
    # <gems_path>/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setter.rb:67:in `set!'
    # <gems_path>/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:38:in `matches?'
    # <gems_path>/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:24:in `each'
    # <gems_path>/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:24:in `detect'
    # <gems_path>/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:24:in `first_passing'
    # <gems_path>/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:534:in `public_send'
    # <gems_path>/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:534:in `run'
    # <gems_path>/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:401:in `does_not_match?'
    # <gems_path>/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/disallow_value_matcher.rb:32:in `matches?'
    # <gems_path>/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/validation_matcher.rb:162:in `run_allow_or_disallow_matcher'
    # <gems_path>/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/validation_matcher.rb:98:in `disallows_value_of'
    # <gems_path>/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/validate_presence_of_matcher.rb:233:in `disallows_original_or_typecast_value?'
    # <gems_path>/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/validate_presence_of_matcher.rb:156:in `block in matches?'
    # <gems_path>/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/validate_presence_of_matcher.rb:155:in `all?'
    # <gems_path>/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/validate_presence_of_matcher.rb:155:in `matches?'
    # ./spec/models/test_spec.rb:4:in `block (2 levels) in <top (required)>'
```

I've created an example repository https://github.com/gmmcal/shoulda-error and the error can be seen in https://travis-ci.com/gmmcal/shoulda-error/builds/115617758

This bug was introduced on `4.1.0`. On `4.0.1` I cannot see this issue happening.

**Comment by mcmire** [comment]
Currently we don't have any tests around ActiveStorage attributes, so that's probably why you're seeing this issue. Happy to take a PR to fix it though!

**Comment by gmmcal** [comment]
I'm just updating the matrix on travis to prove the point. I'll then try to debug and fix the issue. When I have it, happy to open PR :)

**Comment by gmmcal** [comment]
Got to the root cause of the issue.

ActiveStorage associations do not behave the same way as regular associations. It is a special scenario of it. `has_one_attached` actually creates [two associations](https://github.com/rails/rails/blob/master/activestorage/lib/active_storage/attached/model.rb#L49), prepending attribute name with constant strings.

Since the introduction of testing empty string [here](https://github.com/thoughtbot/shoulda-matchers/blob/v4.1.0/lib/shoulda/matchers/active_model/validate_presence_of_matcher.rb#L242), the code tries to test assigning empty string to an active storage object, and that fails. Before, it was only tested using `nil`, and that is successful.

The fix is as easy as checking if `reflect_on_association(@attribute) || reflect_on_association("#{@attribute}_attachment")` is true.

I also considered an `elsif attachment?` [here](https://github.com/thoughtbot/shoulda-matchers/blob/v4.1.0/lib/shoulda/matchers/active_model/validate_presence_of_matcher.rb#L239). I have a feeling this would be less harmful to the entire flow.

Any thoughts @mcmire?

PS: next step is reproduce the bug inside gem suite. With that I can make sure that the bug is gone without harm :)

**Comment by code-later** [comment]
@gmmcal we have the same issue with `daterange` backed columns in PostgreSQL:

```
     NoMethodError:
       undefined method `split' for nil:NilClass
     # ./vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/postgresql/oid/range.rb:71:in `extract_bounds'
     # ./vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/postgresql/oid/range.rb:24:in `cast_value'
     # ./vendor/bundle/ruby/2.6.0/gems/activemodel-5.2.3/lib/active_model/type/value.rb:38:in `cast'
     # ./vendor/bundle/ruby/2.6.0/gems/activemodel-5.2.3/lib/active_model/attribute.rb:175:in `type_cast'
     # ./vendor/bundle/ruby/2.6.0/gems/activemodel-5.2.3/lib/active_model/attribute.rb:42:in `value'
     # ./vendor/bundle/ruby/2.6.0/gems/activemodel-5.2.3/lib/active_model/attribute_set.rb:48:in `fetch_value'
     # ./vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/attribute_methods/read.rb:77:in `_read_attribute'
     # ./vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/attribute_methods/read.rb:40:in `__temp__07562796f646'
     # ./vendor/bundle/ruby/2.6.0/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setter.rb:136:in `public_send'
     # ./vendor/bundle/ruby/2.6.0/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setter.rb:136:in `value_read'
     # ./vendor/bundle/ruby/2.6.0/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setter.rb:140:in `attribute_changed_value?'
     # ./vendor/bundle/ruby/2.6.0/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setter.rb:166:in `raise_attribute_changed_value_error?'
     # ./vendor/bundle/ruby/2.6.0/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setter.rb:88:in `set'
     # ./vendor/bundle/ruby/2.6.0/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setter.rb:67:in `set!'
     # ./vendor/bundle/ruby/2.6.0/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:38:in `matches?'
     # ./vendor/bundle/ruby/2.6.0/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:24:in `each'
     # ./vendor/bundle/ruby/2.6.0/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:24:in `detect'
     # ./vendor/bundle/ruby/2.6.0/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:24:in `first_passing'
     # ./vendor/bundle/ruby/2.6.0/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:534:in `public_send'
     # ./vendor/bundle/ruby/2.6.0/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:534:in `run'
     # ./vendor/bundle/ruby/2.6.0/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:401:in `does_not_match?'
     # ./vendor/bundle/ruby/2.6.0/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/disallow_value_matcher.rb:32:in `matches?'
     # ./vendor/bundle/ruby/2.6.0/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/validation_matcher.rb:162:in `run_allow_or_disallow_matcher'
     # ./vendor/bundle/ruby/2.6.0/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/validation_matcher.rb:98:in `disallows_value_of'
     # ./vendor/bundle/ruby/2.6.0/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/validate_presence_of_matcher.rb:233:in `disallows_original_or_typecast_value?'
     # ./vendor/bundle/ruby/2.6.0/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/validate_presence_of_matcher.rb:156:in `block in matches?'
     # ./vendor/bundle/ruby/2.6.0/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/validate_presence_of_matcher.rb:155:in `all?'
     # ./vendor/bundle/ruby/2.6.0/gems/shoulda-matchers-4.1.0/lib/shoulda/matchers/active_model/validate_presence_of_matcher.rb:155:in `matches?'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-expectations-3.8.3/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-expectations-3.8.3/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-expectations-3.8.3/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-expectations-3.8.3/lib/rspec/expectations/expectation_target.rb:65:in `to'
```

Maybe this helps to further pin that problem down. If I could help provide any additional information please let me know.

**Comment by gmmcal** [comment]
@code-later at first sight, this is an unrelated issue, but they seem to be pin-pointed to the same root cause.

I already have a fix `almost` ready for the issue I presented. If you can come up with a PR on https://github.com/gmmcal/shoulda-error that shows the error you are facing and/or a direction for a fix, I'd be happy to include in my PR.

My current solution is based on a new `if` condition that does not modify current behavior for non-active-storage relations.

**Comment by code-later** [comment]
@gmmcal I'll have a look into this and hopefully come up with some solution as well :)

**Comment by gmmcal** [comment]
@code-later if you need help, let me know. I've just pushed the PR to this issue. You can check at #1224.
