### ISSUE TITLE
Belongs To Relationship Set To Nil

### ISSUE THREAD

**Issue by alauper** [thoughtbot/shoulda-matchers#1307]
Hello, 
I have a test that is failing because the belongs_to relationship is getting set to nil.  It's kind of hard for me to follow all the code, so here's what I see.

My model
app/models/location.rb
```ruby
class Location < ApplicationRecord
  belongs_to :merchant
  # might impact test, so mentioning here
  delegate :pay_with_instant_funding?, :pay_with_ach?, :pay_with_virtual_card?, :pay_with_check?, to: :merchant
   ...
```

Test Case
spec/models/location_spec.rb
```ruby
  let(:merchant) { create :merchant }
  subject { create(:location, merchant: merchant) }

  it { is_expected.to belong_to(:merchant) }
```

I see the following shoulda code

Why is it passing `nil`?
```ruby
shoulda-matchers-4.3.0/lib/shoulda/matchers/active_record/association_matchers/required_matcher.rb
@submatcher = ActiveModel::DisallowValueMatcher.new(nil)
```

Value is `nil`
```ruby
shoulda-matchers-4.3.0/lib/shoulda/matchers/active_model/disallow_value_matcher.rb
@allow_matcher = AllowValueMatcher.new(value)
```
Values is `[nil]`
```ruby
shoulda-matchers-4.3.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb
@values_to_set = values
```
```ruby
shoulda-matchers-4.3.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb
attribute_setters_and_validators_for_values_to_set.public_send(strategy)
```
This will set `merchant` to `nil`
```ruby
shoulda-matchers-4.3.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb
AttributeSettersAndValidators.new(
  self,
  values_to_set.map { |value| [attribute_to_set, value] }
```

Here is my stacktrace
```bash
Failures:

  1) Location relationships is expected to belong to merchant required: true
     Failure/Error: delegate :pay_with_instant_funding?, :pay_with_ach?, :pay_with_virtual_card?, :pay_with_check?, to: :merchant

     Module::DelegationError:
       Location#pay_with_instant_funding? delegated to merchant.pay_with_instant_funding?, but merchant is nil: #<Location id: 3, merchant_id: nil, ...
 # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:426:in `block in make_lambda'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:605:in `catch'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:605:in `block in default_terminator'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:199:in `block in halting'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:513:in `block in invoke_before'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:513:in `each'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:513:in `invoke_before'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:131:in `run_callbacks'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:816:in `_run_validate_callbacks'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/activemodel-5.2.4.3/lib/active_model/validations.rb:409:in `run_validations!'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/activemodel-5.2.4.3/lib/active_model/validations/callbacks.rb:118:in `block in run_validations!'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:132:in `run_callbacks'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:816:in `_run_validation_callbacks'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/activemodel-5.2.4.3/lib/active_model/validations/callbacks.rb:118:in `run_validations!'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/activemodel-5.2.4.3/lib/active_model/validations.rb:339:in `valid?'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/activerecord-5.2.4.3/lib/active_record/validations.rb:67:in `valid?'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/shoulda-matchers-4.3.0/lib/shoulda/matchers/active_model/validator.rb:98:in `perform_validation'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/shoulda-matchers-4.3.0/lib/shoulda/matchers/active_model/validator.rb:91:in `validation_result'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/shoulda-matchers-4.3.0/lib/shoulda/matchers/active_model/validator.rb:87:in `validation_error_messages'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/shoulda-matchers-4.3.0/lib/shoulda/matchers/active_model/validator.rb:66:in `messages'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/shoulda-matchers-4.3.0/lib/shoulda/matchers/active_model/validator.rb:27:in `has_messages?'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/shoulda-matchers-4.3.0/lib/shoulda/matchers/active_model/validator.rb:57:in `messages_match?'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/shoulda-matchers-4.3.0/lib/shoulda/matchers/active_model/validator.rb:23:in `call'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/shoulda-matchers-4.3.0/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:45:in `matches?'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/shoulda-matchers-4.3.0/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:25:in `each'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/shoulda-matchers-4.3.0/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:25:in `detect'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/shoulda-matchers-4.3.0/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:25:in `first_passing'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/shoulda-matchers-4.3.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:536:in `public_send'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/shoulda-matchers-4.3.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:536:in `run'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/shoulda-matchers-4.3.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:402:in `does_not_match?'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/shoulda-matchers-4.3.0/lib/shoulda/matchers/active_model/disallow_value_matcher.rb:33:in `matches?'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/shoulda-matchers-4.3.0/lib/shoulda/matchers/active_record/association_matchers/required_matcher.rb:61:in `submatcher_passes?'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/shoulda-matchers-4.3.0/lib/shoulda/matchers/active_record/association_matchers/required_matcher.rb:23:in `matches?'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/shoulda-matchers-4.3.0/lib/shoulda/matchers/active_record/association_matcher.rb:1212:in `block in failing_submatchers'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/shoulda-matchers-4.3.0/lib/shoulda/matchers/active_record/association_matcher.rb:1211:in `select'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/shoulda-matchers-4.3.0/lib/shoulda/matchers/active_record/association_matcher.rb:1211:in `failing_submatchers'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/shoulda-matchers-4.3.0/lib/shoulda/matchers/active_record/association_matcher.rb:1406:in `submatchers_match?'
     # /Users/adam.lauper/.rvm/gems/ruby-2.6.5@-global/gems/shoulda-matchers-4.3.0/lib/shoulda/matchers/active_record/association_matcher.rb:1157:in `matches?'
     # ./spec/models/location_spec.rb:51:in `block (3 levels) in <top (required)>'
```

**Comment by mcmire** [comment]
This test is failing because in recent versions of Rails, `belongs_to` includes a presence validation to ensure that your association cannot be blank. Therefore, the `belong_to` matcher tests that this validation is in place by attempting to set it to nil. The fact that you are getting an error is revealing an unhandled case in your model, which you can recreate by saying:

``` ruby
create(:location, merchant: nil)
```

Judging by the fact that this error is showing up, it looks like your Location model is calling `pay_with_instant_funding?` automatically when it is saved. As this delegates to the merchant, you will need to account for merchant being nil. Hope this helps!

**Comment by alauper** [comment]
oh yes, it definitely helps!  I appreciate you taking the time to explain that.  🙏
