### ISSUE TITLE
should permit(...).for with Ruby 3 - "wrong number of arguments (given 2, expected 1)"

### ISSUE THREAD

**Issue by jasonsof** [thoughtbot/shoulda-matchers#1496]
Using shoulda 4.0.0 and Ruby 3.0.2 and Rails 6.1.4.4

This was previously fine with Ruby 2.7.4 but upgrading to 3.0.2 produces the following error:

```
RSpec.describe PackagesController, type: :controller do
    it do
        should permit(
        :id,
        :size,
        :checksum
        ).for(:notify,
            params: { id: 1 },
            verb: :post)
    end
end
```

Error: 
```
ArgumentError:
wrong number of arguments (given 2, expected 1)
# ./.bundle/ruby/3.0.0/gems/actionpack-6.1.4.4/lib/action_controller/test_case.rb:405:in `post'
# ./.bundle/ruby/3.0.0/gems/rails-controller-testing-1.0.5/lib/rails/controller/testing/integration.rb:16:in `block (2 levels) in <module:Integration>'
# ./.bundle/ruby/3.0.0/gems/shoulda-matchers-4.5.1/lib/shoulda/matchers/rails_shim.rb:68:in `make_controller_request'
# ./.bundle/ruby/3.0.0/gems/shoulda-matchers-4.5.1/lib/shoulda/matchers/action_controller/permit_matcher.rb:254:in `block in matches?'
# ./.bundle/ruby/3.0.0/gems/shoulda-matchers-4.5.1/lib/shoulda/matchers/doublespeak/world.rb:29:in `with_doubles_activated'
# ./.bundle/ruby/3.0.0/gems/shoulda-matchers-4.5.1/lib/shoulda/matchers/action_controller/permit_matcher.rb:253:in `matches?'
# ./spec/controllers/packages_controller_spec.rb:28:in `block (2 levels) in <top (required)>'
# ./spec/rails_helper.rb:163:in `block (2 levels) in <top (required)>'
```

Is this a bug? Does permit for need to be able to handle deprecations in Ruby 3? (https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/)

**Comment by VSPPedro** [comment]
Would it be possible to update the soulda-mathers gem to the latest version, 5.1.0, and try again?

**Comment by jasonsof** [comment]
That was it 🤦 thank you @VSPPedro !

**Comment by VSPPedro** [comment]
No problem! Thank you!
