### ISSUE TITLE
Wrong error with matcher

### ISSUE THREAD

**Issue by mochetts** [thoughtbot/shoulda-matchers#1582]
# Description

I'm getting a wrong test failure when adding a custom message to a validator

## Model

```rb
class MyModel < ApplicationRecord
  validates :amount, numericality: {
    greater_than_or_equal_to: 3000000,
    message: I18n.t(
      "errors.messages.greater_than_or_equal_to",
      count: ActiveSupport::NumberHelper.number_to_currency(30000)
    )
  }
end
```

## Test
```rb
RSpec.describe MyModel, type: :model do
  subject { build(:my_model) }

  describe "validations" do
    it { should validate_numericality_of(:amount).is_greater_than_or_equal_to(3_000_000) }
  end
end
```

## Error
```bash
1) MyModel validations is expected to validate that :amount looks like a number greater than or equal to 3000000
     Failure/Error: it { should validate_numericality_of(:amount).is_greater_than_or_equal_to(3_000_000) }
     
     NoMethodError:
       undefined method `keys' for #<ActiveModel::Errors [#<ActiveModel::Error attribute=amount, type=greater_than_or_equal_to, options={:message=>"must be greater than or equal to $30,000.00", :value=>2999999, :count=>3000000}>]>
     # /Users/martin/.gem/ruby/3.2.2/gems/shoulda-matchers-4.5.1/lib/shoulda/matchers/active_model/helpers.rb:11:in `format_validation_errors'
     # /Users/martin/.gem/ruby/3.2.2/gems/shoulda-matchers-4.5.1/lib/shoulda/matchers/active_model/validator.rb:37:in `all_formatted_validation_error_messages'
     # /Users/martin/.gem/ruby/3.2.2/gems/shoulda-matchers-4.5.1/lib/shoulda/matchers/active_model/allow_value_matcher.rb:481:in `failure_message_when_negated'
     # /Users/martin/.gem/ruby/3.2.2/gems/shoulda-matchers-4.5.1/lib/shoulda/matchers/active_model/disallow_value_matcher.rb:65:in `failure_message'
     # /Users/martin/.gem/ruby/3.2.2/gems/shoulda-matchers-4.5.1/lib/shoulda/matchers/active_model/numericality_matchers/comparison_matcher.rb:79:in `failure_message'
     # /Users/martin/.gem/ruby/3.2.2/gems/shoulda-matchers-4.5.1/lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb:637:in `public_send'
     # /Users/martin/.gem/ruby/3.2.2/gems/shoulda-matchers-4.5.1/lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb:637:in `build_submatcher_failure_message_for'
     # /Users/martin/.gem/ruby/3.2.2/gems/shoulda-matchers-4.5.1/lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb:620:in `failure_message_for_first_submatcher_that_fails_to_match'
     # /Users/martin/.gem/ruby/3.2.2/gems/shoulda-matchers-4.5.1/lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb:474:in `block in failure_message'
     # /Users/martin/.gem/ruby/3.2.2/gems/shoulda-matchers-4.5.1/lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb:472:in `failure_message'
     # ./spec/models/my_model_request_spec.rb:7:in `block (3 levels) in <top (required)>'
```

However, if I remove the custom message the test passes.

**Comment by mochetts** [comment]
Edit:

The test passes if I do:

```rb
describe "validations" do
    it {
      should validate_numericality_of(:amount).is_greater_than_or_equal_to(3_000_000).with_message(I18n.t(
        "errors.messages.greater_than_or_equal_to",
        count: ActiveSupport::NumberHelper.number_to_currency(30000)
      ))
    }
  end
```

I still think the error presented is not friendly enough.

**Comment by matsales28** [comment]
Hey @mochetts, thanks for opening this issue. I'll take a look as soon as I have some time!

**Comment by matsales28** [comment]
Hi @mochetts can you try to share a reproducible script of this error? I wasn't able to replicate this error. I know by the log you sent that you are using `shoulda-matchers`-4.5.1 and Ruby 3.2.2, but the Rails version might have an impact here.

**Comment by mochetts** [comment]
Hey! Using 7.1.2

**Comment by mochetts** [comment]
<img width="1421" alt="Screenshot 2023-12-25 at 9 40 42 AM" src="https://github.com/thoughtbot/shoulda-matchers/assets/3678598/def0c14a-8fd0-4b44-9a45-8b9aaef2ea20">

**Comment by mochetts** [comment]
My rails_helper.rb:

```rb
# This file is copied to spec/ when you run 'rails generate rspec:install'
require "spec_helper"
ENV["RAILS_ENV"] ||= "test"
require_relative "../config/environment"
# Prevent database truncation if the environment is production
abort("The Rails environment is running in production mode!") if Rails.env.production?
require "rspec/rails"
require "capybara/rails"
require Rails.root.join("test_helpers/base_test_helper")
require "capybara/cuprite"
require "capybara-screenshot/rspec"
require "active_storage_validations/matchers"
require "pundit/matchers"
require "pundit/rspec"
Dir[Rails.root.join("spec/features/support/**/*.rb")].sort.each { |f| require f }
require "active_support"
require "active_support/testing/time_helpers"

# Add additional requires below this line. Rails is not loaded until this point!

# Requires supporting ruby files with custom matchers and macros, etc, in
# spec/support/ and its subdirectories. Files matching `spec/**/*_spec.rb` are
# run as spec files by default. This means that files in spec/support that end
# in _spec.rb will both be required and run as specs, causing the specs to be
# run twice. It is recommended that you do not name files matching this glob to
# end with _spec.rb. You can configure this pattern with the --pattern
# option on the command line or in ~/.rspec, .rspec or `.rspec-local`.
#
# The following line is provided for convenience purposes. It has the downside
# of increasing the boot-up time by auto-requiring all files in the support
# directory. Alternatively, in the individual `*_spec.rb` files, manually
# require only the support files necessary.
#
# Dir[Rails.root.join('spec', 'support', '**', '*.rb')].sort.each { |f| require f }

# Checks for pending migrations and applies them before tests are run.
# If you are not using ActiveRecord, you can remove these lines.
begin
  ActiveRecord::Migration.maintain_test_schema!
rescue ActiveRecord::PendingMigrationError => e
  abort e.to_s.strip
end

Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    with.test_framework :rspec
    with.library :rails
  end
end

def non_empty_pdf
  file = Rack::Test::UploadedFile.new(Rails.root.join("spec/fixtures/files/non_empty.pdf"))
  ActiveStorage::Blob.create_and_upload!(
    io: file.open,
    filename: file.original_filename,
    content_type: file.content_type
  )
end

# Configure capybara to use cuprite driver for javascript tests
Capybara.register_driver(:cuprite) do |app|
  # Unlike the capybara timeout, which should be very short to ensure test fail
  # fast, this timeout needs to be long to ensure we give enough time for assets
  # to be precompiled.
  #
  # You can increase this value in `.env.development.local` in slower matchines.
  cuprite_timeout = ENV.fetch("CUPRITE_TIMEOUT", 30).to_i

  Capybara::Cuprite::Driver.new(
    app,
    js_errors: true,
    browser_options: {
      "no-sandbox" => nil,
      "disable-dev-shm-usage" => nil,
      "disable-site-isolation-trials" => nil
    },
    timeout: cuprite_timeout,
    process_timeout: cuprite_timeout,
    inspector: !ENV["CI"],
    headless: %w[true 1 yes].include?(ENV["HEADLESS"] || ENV["CI"]),
    slowmo: (ENV["SLOWMO"] == "true") ? 0.1 : ENV["SLOWMO"],
    logger: CustomCupriteLogger.new
  )
end
Capybara.javascript_driver = :cuprite
Capybara.default_driver = :cuprite

def open_file_fixture(file_name)
  File.open(file_fixture(file_name))
end

RSpec.configure do |config|
  config.include RSpec::Rails::RequestExampleGroup, type: :request

  # Remove this line if you're not using ActiveRecord or ActiveRecord fixtures
  config.fixture_path = "#{::Rails.root}/spec/fixtures"
  config.global_fixtures = :all

  # If you're not using ActiveRecord, or you'd prefer not to run each of your
  # examples within a transaction, remove the following line or assign false
  # instead of true.
  config.use_transactional_fixtures = true

  # You can uncomment this line to turn off ActiveRecord support entirely.
  # config.use_active_record = false

  # RSpec Rails can automatically mix in different behaviours to your tests
  # based on their file location, for example enabling you to call `get` and
  # `post` in specs under `spec/controllers`.
  #
  # You can disable this behaviour by removing the line below, and instead
  # explicitly tag your specs with their type, e.g.:
  #
  #     RSpec.describe UsersController, type: :controller do
  #       # ...
  #     end
  #
  # The different available types are documented in the features, such as in
  # https://rspec.info/features/6-0/rspec-rails
  # config.infer_spec_type_from_file_location!

  # Filter lines from Rails gems in backtraces.
  config.filter_rails_from_backtrace!
  # arbitrary gems may also be filtered via:
  # config.filter_gems_from_backtrace("gem name")

  config.include ActiveJob::TestHelper
  config.include ActiveStorageValidations::Matchers
  config.include DefaultTestHelpers, type: :feature
  config.include ActiveSupport::Testing::TimeHelpers

  ActiveStorage::Current.url_options = {host: "https://www.example.com"}
end
```

**Comment by mochetts** [comment]
My `spec_helper.rb`

```rb
require "inertia_rails/rspec"
require "capybara/rspec"
require "capybara_test_helpers/rspec"

# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# See https://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  # rspec-expectations config goes here. You can use an alternate
  # assertion/expectation library such as wrong or the stdlib/minitest
  # assertions if you prefer.
  config.expect_with :rspec do |expectations|
    # This option will default to `true` in RSpec 4. It makes the `description`
    # and `failure_message` of custom matchers include text for helper methods
    # defined using `chain`, e.g.:
    #     be_bigger_than(2).and_smaller_than(4).description
    #     # => "be bigger than 2 and smaller than 4"
    # ...rather than:
    #     # => "be bigger than 2"
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library (such as bogus or mocha) by changing the `mock_with` option here.
  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended, and will default to
    # `true` in RSpec 4.
    mocks.verify_partial_doubles = true
  end

  # This option will default to `:apply_to_host_groups` in RSpec 4 (and will
  # have no way to turn it off -- the option exists only for backwards
  # compatibility in RSpec 3). It causes shared context metadata to be
  # inherited by the metadata hash of host groups and examples, rather than
  # triggering implicit auto-inclusion in groups with matching metadata.
  config.shared_context_metadata_behavior = :apply_to_host_groups
end

RSpec::Matchers.define :be_the_same_date_as do |expected|
  match do |actual|
    expect(expected.strftime("%d/%m/%Y")).to eq(actual.strftime("%d/%m/%Y"))
  end
end

RSpec::Matchers.define :be_the_same_time_as do |expected|
  match do |actual|
    expect(expected.strftime("%d/%m/%Y %H:%M:%S")).to eq(actual.strftime("%d/%m/%Y %H:%M:%S"))
  end
end
```

**Comment by mochetts** [comment]
There are 2 errors when the object gets validated.. maybe that's the key. The other error was fixed as stated in https://github.com/thoughtbot/shoulda-matchers/issues/1583. Maybe this got fixed with that as well?

**Comment by amalrik** [comment]
@mochetts can you share your factory_bot file for that model?

**Comment by mochetts** [comment]
I'm using fixtures

```yml
wonka_incomplete:
  amount: 4000000
  avg_draw_amount: 4000000
  company: wonka
  status: incomplete
```

Trimmed down version of the spec:

```rb
require "rails_helper"

RSpec.describe CreditLineRequest, type: :model do
  subject { credit_line_requests(:wonka_incomplete) }

  describe "validations" do
    it {
      should validate_numericality_of(:amount).is_greater_than_or_equal_to(50_00_00).with_message(I18n.t(
        "errors.messages.greater_than_or_equal_to",
        count: ActiveSupport::NumberHelper.number_to_currency(5000)
      ))
    }
end
```

Trimmed down version of the model:

```rb
class CreditLineRequest < ApplicationRecord
  belongs_to :company

  validates :amount, :avg_draw_amount, presence: true
  validates :amount, numericality: {
    greater_than_or_equal_to: 5_000_00,
    message: I18n.t(
      "errors.messages.greater_than_or_equal_to",
      count: ActiveSupport::NumberHelper.number_to_currency(5000)
    )
  }
  validates :avg_draw_amount, numericality: {
    less_than_or_equal_to: ->(request) { request.amount || 0 },
    message: I18n.t(
      "errors.messages.less_than_or_equal_to",
      count: I18n.t("activerecord.attributes.credit_line_request.amount")
    )
  }
end
```

**Comment by amalrik** [comment]
I'm still unable to reproduce the error. :thinking:

**Comment by mochetts** [comment]
@amalrik are you using the latest commit on main? Because there's a chance that this was fixed in https://github.com/thoughtbot/shoulda-matchers/pull/1552

**Comment by matsales28** [comment]
@mochetts this commit https://github.com/thoughtbot/shoulda-matchers/commit/7663821cff15235d1dc8ffc61ca7e8c5e701dc52 seems to be fixing this problem. But the main issue is that your validations are "dependent" on each other, which makes the way `shoulda-matchers` uses to check the validations return multiple errors, not a single one. 

The code did not support that, and the commit I linked makes this adjusment.

**Comment by amalrik** [comment]
> @amalrik are you using the latest commit on main? Because there's a chance that this was fixed by https://github.com/thoughtbot/shoulda-matchers/pull/1552

I'm actually using the last stable release I think it's 5.3.0

**Comment by mochetts** [comment]
@matsales28 @amalrik alright I think I figured it out... I included "shoulda" in the gemfile which pulled "shoulda-matchers" version 4.0.0. So I wasn't pulling all those fixes.

After removing the "shoulda" dependency from the gemfile and instead including the right shoulda matcher dependeny:
```rb
gem "shoulda-matchers", "~> 6.0"
```

The error is no longer reproduced.

Thanks for your patience and help!

**Comment by amalrik** [comment]
> @matsales28 @amalrik alright I think I figured it out... I included "shoulda" in the gemfile which pulled "shoulda-matchers" version 4.0.0. So I wasn't pulling all those fixes. The reason of the stale "should-matchers" version is this line:
> https://github.com/thoughtbot/shoulda/blob/main/shoulda.gemspec#L32
> 
> After removing the "shoulda" dependency from the gemfile and instead include the right "shoulda-matchers" dependency:
> ```rb
> gem "shoulda-matchers", "~> 6.0"
> ```
> 
> The error is no longer reproduced.
> 
> Thanks for your patience and help! 🙏🏻 

Amazing and I'm glad I could help
