### ISSUE TITLE
validates_presence_of ignores my after_initialize method, causing it to fail.

### ISSUE THREAD

**Issue by draffauf** [thoughtbot/shoulda-matchers#297]
```
13:53:06 guard.1 |   4) LineItem 
13:53:06 guard.1 |      Failure/Error: it { should validate_presence_of(:quantity).with_message("Please enter a quantity.") }
13:53:06 guard.1 |      NoMethodError:
13:53:06 guard.1 |        undefined method `*' for nil:NilClass
13:53:06 guard.1 |      # ./app/models/line_item.rb:147:in `total_price'
13:53:06 guard.1 |      # ./app/models/line_item.rb:217:in `set_price'
13:53:06 guard.1 |      # ./spec/models/line_item_spec.rb:32:in `block (2 levels) in <top (required)>'

# /app/models/line_item:
...
after_initialize :init
before_validation :set_document, :set_product, :set_price
...
def init
  self.provided_on  ||= Date.today      
  self.quantity         ||= 0
  self.unit_price       ||= 0
end

def set_price
  self.price = total_price
end

def total_price
  quantity * unit_price
end
...
```

**Comment by zzeniou86** [comment]
subject { LineItem.new } should fix this.

**Comment by mcmire** [comment]
The default subject is `described_class.new`, so that wouldn't fix this.

Checking for `quantity` to be nil inside of `total_price` would, though.
