### ISSUE TITLE
Uniqueness validations pg non-null error for wrong column

### ISSUE THREAD

**Issue by stephen-puiszis** [thoughtbot/shoulda-matchers#600]
Cannot figure out what's going on. The test is failing on the `uid` uniquness matcher, but for a non-null violation on the `first_name` column, even though the first-name column matcher is passing. `uid` is an optional db column for if a user signs-up via omniauth like facebook or linkedin login. I'm creating valid objects prior to running the tests using FactoryGirl and have tried explicitly setting the column values before running the tests. I've dropped all the tables, re-migrated and still have issues. I've changed syntaxes, used expect vs. should and am out of ideas of what is causing this test to fail. Below is reference of the other places I've tried solutions from.  Rails version 4.0.5, rspec with shoulda in the test group.  
- https://github.com/thoughtbot/shoulda-matchers/issues/572
- https://github.com/thoughtbot/shoulda-matchers/issues/336
- https://github.com/thoughtbot/shoulda-matchers/issues/402
- https://github.com/rails/rails/issues/5529
- http://stackoverflow.com/questions/23543349/how-do-i-interpret-this-rails-postgresql-error
- http://stackoverflow.com/questions/16156039/rspec-rails-and-testing-validates-uniquess-of-with-scope

```
Failure/Error: it { should validate_uniqueness_of(:uid).allow_nil }
     ActiveRecord::StatementInvalid:
       PG::NotNullViolation: ERROR:  null value in column "first_name" violates not-null constraint
       DETAIL:  Failing row contains (110, , , null, null, null, 0, null, null, null, null, 8b1502d6d14a267788d9c06c0412428a4be235f8c4b5b01c8a0d14a1790ff0d3, null, 2014-10-17 04:40:19.569064, null, 2014-10-17 04:40:19.373726, 2014-10-17 04:40:19.373726, null, null, null, null, a).
       : INSERT INTO "users" ("confirmation_sent_at", "confirmation_token", "created_at", "uid", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"
```

```ruby
#spec/models/user_spec.rb
require "spec_helper"

describe User do
  let(:user) { create :user}

  it { should have_db_column(:first_name).of_type(:string).with_options(null: false) }
  it { should have_db_column(:last_name).of_type(:string).with_options(null: false) }
  it { should have_db_column(:phone_number).of_type(:string) }

  it { should have_one(:professional_profile).dependent(:destroy) }

  it { should respond_to(:first_name) }
  it { should respond_to(:last_name) }
  it { should respond_to(:phone_number) }

  describe 'validations' do
    subject { build(:user, first_name: "Hello") }
    it { should validate_presence_of(:first_name) }
    it { should validate_presence_of(:last_name) }
    it { should validate_uniqueness_of(:uid).allow_nil }
  end
...

#models/user.rb
class User < ActiveRecord::Base
rolify
...
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable,
         omniauth_providers: [:linkedin]

  validates :first_name, presence: true
  validates :last_name,  presence: true
  validates :uid,        uniqueness: true, allow_nil: true
...
```

**Comment by mcmire** [comment]
Since this seems to be an unexplainable edge case, and a workaround exists, I'm going to go ahead and close this issue. Feel free to comment if you find a solution, though.

**Comment by rafaelgonzalez** [comment]
This happens to me as well when I have a non-null constraint on my model.

```ruby
# db/migrate/create_channel_articles.rb

class CreateChannelArticles < ActiveRecord::Migration
  def change
    create_table :channel_articles do |t|
      t.integer :article_id, null: false, index: true
      t.integer :channel_id, null: false, index: true

      t.index [:article_id, :channel_id], unique: true

      t.timestamps null: false
    end
  end
end
```

```ruby
# app/model/channel_article.rb

class ChannelArticle < ActiveRecord::Base
  belongs_to :article
  belongs_to :channel

  validates :article, :channel, presence: true
  validates :article_id, uniqueness: { scope: :channel_id }
end
```

```ruby
# specs/models/channel_article_spec.rb

require 'rails_helper'

RSpec.describe ChannelArticle, type: :model do
  it { should belong_to(:article) }
  it { should belong_to(:channel) }

  it { should validate_presence_of(:article) }
  it { should validate_presence_of(:channel) }
 
  it { should validate_uniqueness_of(:article_id).scoped_to(:channel_id) }
end
```

I get the following:

```
1) ChannelArticle should require case sensitive unique value for article scoped to channel
     Failure/Error: it { should validate_uniqueness_of(:article).scoped_to(:channel) }
     ActiveRecord::AssociationTypeMismatch:
       Article(#70302512837760) expected, got String(#70302462052200)
     # /Users/rafaelgonzalez/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/associations/association.rb:216:in `raise_on_type_mismatch!'
     # /Users/rafaelgonzalez/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/associations/belongs_to_association.rb:12:in `replace'
     # /Users/rafaelgonzalez/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/associations/singular_association.rb:17:in `writer'
     # /Users/rafaelgonzalez/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/associations/builder/association.rb:123:in `article='
     # /Users/rafaelgonzalez/.rvm/gems/ruby-2.2.1/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb:304:in `block in create_record_in_database'
     # /Users/rafaelgonzalez/.rvm/gems/ruby-2.2.1/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb:303:in `tap'
     # /Users/rafaelgonzalez/.rvm/gems/ruby-2.2.1/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb:303:in `create_record_in_database'
     # /Users/rafaelgonzalez/.rvm/gems/ruby-2.2.1/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb:279:in `first_instance'
     # /Users/rafaelgonzalez/.rvm/gems/ruby-2.2.1/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb:275:in `existing_record'
     # /Users/rafaelgonzalez/.rvm/gems/ruby-2.2.1/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb:335:in `block in set_scoped_attributes'
     # /Users/rafaelgonzalez/.rvm/gems/ruby-2.2.1/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb:332:in `each'
     # /Users/rafaelgonzalez/.rvm/gems/ruby-2.2.1/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb:332:in `all?'
     # /Users/rafaelgonzalez/.rvm/gems/ruby-2.2.1/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb:332:in `set_scoped_attributes'
     # /Users/rafaelgonzalez/.rvm/gems/ruby-2.2.1/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb:245:in `matches?'
     # ./spec/models/channel_article_spec.rb:11:in `block (2 levels) in <top (required)>'
```

It's like it is creating the model without setting the attributes that have null constraints on them. If I remove the non-null constraint from my migration and regenerate the DB, the tests pass.

**Comment by rafaelgonzalez** [comment]
Also note that doing

```ruby
# app/model/channel_article.rb
validates :article_id, uniqueness: { scope: :channel_id }

# specs/models/channel_article_spec.rb
it { should validate_uniqueness_of(:article_id).scoped_to(:channel_id) }
```

Leads me to this other problem: #535

**Comment by rafaelgonzalez** [comment]
Most likely related to #194 as well.

**Comment by mcmire** [comment]
@rafaelgonzalez Yeah, your issue is related to #194. But this is different -- here, none of the columns in the uniqueness validation involve `first_name`, so there should be no reason that the null constraint should be getting violated.
