### ISSUE TITLE
inclusion: the outside value may be outside the allowable max value of the column

### ISSUE THREAD

**Issue by dammer** [thoughtbot/shoulda-matchers#634]
I have spec which fail after upgrade to rails 4.2 from 4.1

```Ruby
# some model validation spec 
is_expected.to validate_inclusion_of(:market_id).in_array(Markets.codes + Markets.entries)
```
also 

```
irb(main):012:0> Markets.codes
=> [1, 2, 3]

irb(main):014:0> Markets.entries
=> [Markets::Th, Markets::Id, Markets::Ph]

irb(main):018:0> Markets.entries.map(&:to_i)
=> [1, 2, 3]
```

```Ruby
#scheme definion
t.integer  "market_id",                   limit: 2,                   null: false
```

```Ruby
#model
validates :market_id, inclusion: { in: (Markets.codes + Markets.entries) }, on: :create
```

```
  # backtrace
  1) market_id
     Failure/Error: is_expected.to validate_inclusion_of(:market_id).in_array(Markets.codes + Markets.entries)
     RangeError:
       123456789 is out of range for ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Integer with limit 2
     # ./.bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/type/integer.rb:41:in `ensure_in_range'
     # ./.bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/type/integer.rb:34:in `cast_value'
     # ./.bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/type/value.rb:89:in `type_cast'
     # ./.bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/type/numeric.rb:15:in `type_cast'
     # ./.bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/type/value.rb:34:in `type_cast_from_user'
     # ./.bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/attribute.rb:100:in `type_cast'
     # ./.bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/attribute.rb:42:in `original_value'
     # ./.bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/attribute.rb:37:in `value'
     # ./.bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/attribute.rb:46:in `value_for_database'
     # ./.bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:164:in `store_original_raw_attribute'
     # ./.bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:93:in `write_attribute'
     # ./.bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/attribute_methods.rb:50:in `__temp__d61627b65647f59646'
     # ./.bundle/ruby/2.1.0/gems/shoulda-matchers-2.7.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:247:in `set_value'
     # ./.bundle/ruby/2.1.0/gems/shoulda-matchers-2.7.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:221:in `block in matches?'
     # ./.bundle/ruby/2.1.0/gems/shoulda-matchers-2.7.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:219:in `each'
     # ./.bundle/ruby/2.1.0/gems/shoulda-matchers-2.7.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:219:in `none?'
     # ./.bundle/ruby/2.1.0/gems/shoulda-matchers-2.7.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:219:in `matches?'
     # ./.bundle/ruby/2.1.0/gems/shoulda-matchers-2.7.0/lib/shoulda/matchers/active_model/validation_matcher.rb:43:in `allows_value_of'
     # ./.bundle/ruby/2.1.0/gems/shoulda-matchers-2.7.0/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:412:in `disallows_value_outside_of_array?'
     # ./.bundle/ruby/2.1.0/gems/shoulda-matchers-2.7.0/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:350:in `matches_for_array?'
     # ./.bundle/ruby/2.1.0/gems/shoulda-matchers-2.7.0/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:328:in `matches?'
     # ./spec/models/user/market_spec.rb:5:in `block (2 levels) in <top (required)>'
```

**Comment by dammer** [comment]
@mcmire yes, this true for 2.8.0.rc1
```
     Failure/Error: is_expected.to validate_inclusion_of(:market_id).in_array(Markets.codes + Markets.entries)
     RangeError:
       123456789 is out of range for ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Integer with limit 2
     # ./.bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/type/integer.rb:41:in `ensure_in_range'
     # ./.bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/type/integer.rb:34:in `cast_value'
     # ./.bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/type/value.rb:89:in `type_cast'
     # ./.bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/type/numeric.rb:15:in `type_cast'
     # ./.bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/type/value.rb:34:in `type_cast_from_user'
     # ./.bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/attribute.rb:100:in `type_cast'
     # ./.bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/attribute.rb:42:in `original_value'
     # ./.bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/attribute.rb:37:in `value'
     # ./.bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/attribute.rb:46:in `value_for_database'
     # ./.bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:164:in `store_original_raw_attribute'
     # ./.bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:93:in `write_attribute'
     # ./.bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/attribute_methods.rb:50:in `__temp__d61627b65647f59646'
     # ./.bundle/ruby/2.1.0/gems/shoulda-matchers-2.8.0.rc1/lib/shoulda/matchers/active_model/allow_value_matcher.rb:247:in `set_value'
     # ./.bundle/ruby/2.1.0/gems/shoulda-matchers-2.8.0.rc1/lib/shoulda/matchers/active_model/allow_value_matcher.rb:221:in `block in matches?'
     # ./.bundle/ruby/2.1.0/gems/shoulda-matchers-2.8.0.rc1/lib/shoulda/matchers/active_model/allow_value_matcher.rb:219:in `each'
     # ./.bundle/ruby/2.1.0/gems/shoulda-matchers-2.8.0.rc1/lib/shoulda/matchers/active_model/allow_value_matcher.rb:219:in `none?'
     # ./.bundle/ruby/2.1.0/gems/shoulda-matchers-2.8.0.rc1/lib/shoulda/matchers/active_model/allow_value_matcher.rb:219:in `matches?'
     # ./.bundle/ruby/2.1.0/gems/shoulda-matchers-2.8.0.rc1/lib/shoulda/matchers/active_model/validation_matcher.rb:43:in `allows_value_of'
     # ./.bundle/ruby/2.1.0/gems/shoulda-matchers-2.8.0.rc1/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:413:in `block in disallows_value_outside_of_array?'
     # ./.bundle/ruby/2.1.0/gems/shoulda-matchers-2.8.0.rc1/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:412:in `each'
     # ./.bundle/ruby/2.1.0/gems/shoulda-matchers-2.8.0.rc1/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:412:in `any?'
     # ./.bundle/ruby/2.1.0/gems/shoulda-matchers-2.8.0.rc1/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:412:in `disallows_value_outside_of_array?'
     # ./.bundle/ruby/2.1.0/gems/shoulda-matchers-2.8.0.rc1/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:350:in `matches_for_array?'
     # ./.bundle/ruby/2.1.0/gems/shoulda-matchers-2.8.0.rc1/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:328:in `matches?'
```

**Comment by dolzenko** [comment]
Same issue here, I wonder if [0] should respect the column limits, or should just calculate outside value instead of using hardcoded one (which overflows the column)

[0] https://github.com/thoughtbot/shoulda-matchers/blob/5f8c3235d0e497fbc096ffc25ffa5482010bd0fc/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb#L429

**Comment by nathany** [comment]
Seeing essentially the same issue when upgrading to Rails 4.2, but with:

```ruby
is_less_than_or_equal_to(2_147_483_647)
```

```
2147483648 is out of range for ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Integer with limit 4
```

I tried upgrading to 2.8.0.rc1 but still had the issue.

**Comment by mcmire** [comment]
@nathany But 2147483648 *is* out of range for an integer with a limit of 4. I'm curious how this was working before...

Did something change in Rails 4.2 with regard to integer columns?

**Comment by mcmire** [comment]
Oh this is probably related to stuff that @sgrif did with typecasting and so forth.

**Comment by mcmire** [comment]
So looks like we have two issues here:

* For `validate_inclusion_of`, the outside value chosen may exceed the allowable max value of the column
* For `validate_numericality_of`, if you use one less than the allowable max value of the column then you'll get an error

I'll rename this issue for the first case and make a new issue for the second one.

**Comment by sgrif** [comment]
Yeah, the range stuff is new in 4.2. The reasoning is a long story, which I can give you the details of if you want, but the TL;DR is that if we don't do this, some databases will raise an exception some of the time, and it's better for us to just always give an exception in a known place so it can be caught and handled if needed (which we do in methods like `find` and `find_by`)

**Comment by sgrif** [comment]
@nathany If you're testing `is_less_than_or_equal_to(2_147_483_647)`, you can just remove the validation. It is impossible to persist that value in Rails 4.2+ on 32-bit signed integer columns.

**Comment by sgrif** [comment]
For the issue with `validate_inclusion_of`, it should be safe to just `rescue RangeError` in `allow_value`, and treat the value as dis-allowed. That should fix all of the issues mentioned in this thread. Unless the user has a custom writer which could potentially raise a `RangeError`, this is the only place that a `RangeError` should come from.

**Comment by nathany** [comment]
@sgrif Thanks. That's what I ended up doing. Though I still have the validation itself in place. I haven't looked into how Rails 4.2 presents the error to a user when the validation isn't there.

**Comment by mcmire** [comment]
Fixed by #642.

**Comment by andreierdoss** [comment]
I am getting this error 
`123456789 is out of range for ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Integer with limit 2`
when I try to use 
`it { is_expected.to validate_inclusion_of(:value).in_array([-1, 1]) }`. 
I assume that this issue is related.

I'm not too clear on what I need to do to overcome it. I didn't see anything in the documentation to address it. Please advise.

**Comment by mcmire** [comment]
@andreierdoss Sorry for the delay on this. Which version of the gem are you using?
