### ISSUE TITLE
Cannot open rails console without getting circular argument reference warning. 

### ISSUE THREAD

**Issue by Tearistturnip** [thoughtbot/shoulda-matchers#754]
/Users/TURNIPZ/.rvm/gems/ruby-2.2.1/gems/activesupport-3.2.13/lib/active_support/values/time_zone.rb:270: warning: circular argument reference - now
    /Users/TURNIPZ/.rvm/gems/ruby-2.2.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require': cannot load such file -- test/unit/testcase (LoadError)
    from /Users/TURNIPZ/.rvm/gems/ruby-2.2.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `block in require'
    from /Users/TURNIPZ/.rvm/gems/ruby-2.2.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /Users/TURNIPZ/.rvm/gems/ruby-2.2.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
    from /Users/TURNIPZ/.rvm/gems/ruby-2.2.1/gems/activesupport-3.2.13/lib/active_support/test_case.rb:1:in `<top (required)>'
    from /Users/TURNIPZ/.rvm/gems/ruby-2.2.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
    from /Users/TURNIPZ/.rvm/gems/ruby-2.2.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `block in require'
    from /Users/TURNIPZ/.rvm/gems/ruby-2.2.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /Users/TURNIPZ/.rvm/gems/ruby-2.2.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
    from /Users/TURNIPZ/.rvm/gems/ruby-2.2.1/gems/railties-3.2.13/lib/rails/console/app.rb:2:in `<top (required)>'
    from /Users/TURNIPZ/.rvm/gems/ruby-2.2.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
    from /Users/TURNIPZ/.rvm/gems/ruby-2.2.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `block in require'
    from /Users/TURNIPZ/.rvm/gems/ruby-2.2.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /Users/TURNIPZ/.rvm/gems/ruby-2.2.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
    from /Users/TURNIPZ/.rvm/gems/ruby-2.2.1/gems/railties-3.2.13/lib/rails/application.rb:304:in `initialize_console'
    from /Users/TURNIPZ/.rvm/gems/ruby-2.2.1/gems/railties-3.2.13/lib/rails/application.rb:152:in `load_console'
    from /Users/TURNIPZ/.rvm/gems/ruby-2.2.1/gems/railties-3.2.13/lib/rails/commands/console.rb:27:in `start'
    from /Users/TURNIPZ/.rvm/gems/ruby-2.2.1/gems/railties-3.2.13/lib/rails/commands/console.rb:8:in `start'
    from /Users/TURNIPZ/.rvm/gems/ruby-2.2.1/gems/railties-3.2.13/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'

Need help with resolving this issue. I'm going through a rails tutorial and I need to access the rails console. I'm on ruby version 2.2.2 and on rails 3.2.13. Much help would be appreciated. Not sure but this might have to do with the issue , not sure though. I'm a beginner at rails and programming in general, so I'll probably need a step by step guide.

**Comment by Tearistturnip** [comment]
sorry i posted this in the wrong place
