### ISSUE TITLE
Unable to run individual specs via appraisal

### ISSUE THREAD

**Issue by jc00ke** [thoughtbot/shoulda-matchers#758]
From #757 

```
> appraisal 4.2 rspec spec/unit/shoulda/matchers/active_record/serialize_matcher_spec.rb 
WARN: Unresolved specs during Gem::Specification.reset:
      rake (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
>> BUNDLE_GEMFILE=/home/jesse/projects/shoulda-matchers/gemfiles/4.2.gemfile bundle exec rspec spec/unit/shoulda/matchers/active_record/serialize_matcher_spec.rb
Could not find rdoc-4.2.0 in any of the sources
Run `bundle install` to install missing gems.

> appraisal install
WARN: Unresolved specs during Gem::Specification.reset:
      rake (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
>> bundle check --gemfile='/home/jesse/projects/shoulda-matchers/gemfiles/4.0.0.gemfile' || bundle install --gemfile='/home/jesse/projects/shoulda-matchers/gemfiles/4.0.0.gemfile'
The Gemfile's dependencies are satisfied
>> bundle check --gemfile='/home/jesse/projects/shoulda-matchers/gemfiles/4.0.1.gemfile' || bundle install --gemfile='/home/jesse/projects/shoulda-matchers/gemfiles/4.0.1.gemfile'
The Gemfile's dependencies are satisfied
>> bundle check --gemfile='/home/jesse/projects/shoulda-matchers/gemfiles/4.1.gemfile' || bundle install --gemfile='/home/jesse/projects/shoulda-matchers/gemfiles/4.1.gemfile'
The Gemfile's dependencies are satisfied
>> bundle check --gemfile='/home/jesse/projects/shoulda-matchers/gemfiles/4.2.gemfile' || bundle install --gemfile='/home/jesse/projects/shoulda-matchers/gemfiles/4.2.gemfile'
The Gemfile's dependencies are satisfied


> appraisal 4.2 rspec spec/unit/shoulda/matchers/active_record/serialize_matcher_spec.rb 
WARN: Unresolved specs during Gem::Specification.reset:
      rake (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
>> BUNDLE_GEMFILE=/home/jesse/projects/shoulda-matchers/gemfiles/4.2.gemfile bundle exec rspec spec/unit/shoulda/matchers/active_record/serialize_matcher_spec.rb
Could not find rdoc-4.2.0 in any of the sources
Run `bundle install` to install missing gems.
```

@maurogeorge?

**Comment by maurogeorge** [comment]
Hi @jc00ke `$ bundle && bundle exec rake` passes all tests? Maybe you need to do `$ bundle exec appraisal 4.2 rspec spec/unit/shoulda/matchers/active_record/serialize_matcher_spec.rb`

**Comment by jc00ke** [comment]
Hmm, I tried both and neither worked :frowning: 

```
> bundle exec rake --trace
** Invoke default (first_time)
** Execute default
** Invoke appraise (first_time)
** Execute appraise
>> bundle check --gemfile='/home/jesse/projects/shoulda-matchers/gemfiles/4.0.0.gemfile' || bundle install --gemfile='/home/jesse/projects/shoulda-matchers/gemfiles/4.0.0.gemfile'
The Gemfile's dependencies are satisfied
>> bundle check --gemfile='/home/jesse/projects/shoulda-matchers/gemfiles/4.0.1.gemfile' || bundle install --gemfile='/home/jesse/projects/shoulda-matchers/gemfiles/4.0.1.gemfile'
The Gemfile's dependencies are satisfied
>> bundle check --gemfile='/home/jesse/projects/shoulda-matchers/gemfiles/4.1.gemfile' || bundle install --gemfile='/home/jesse/projects/shoulda-matchers/gemfiles/4.1.gemfile'
The Gemfile's dependencies are satisfied
>> bundle check --gemfile='/home/jesse/projects/shoulda-matchers/gemfiles/4.2.gemfile' || bundle install --gemfile='/home/jesse/projects/shoulda-matchers/gemfiles/4.2.gemfile'
The Gemfile's dependencies are satisfied
>> BUNDLE_GEMFILE=/home/jesse/projects/shoulda-matchers/gemfiles/4.0.0.gemfile bundle exec rake
rake spec:unit
rake aborted!
Command failed with status (1): [rake spec:unit...]
/home/jesse/projects/shoulda-matchers/Rakefile:24:in `block in <top (required)>'
Tasks: TOP => default
(See full trace by running task with --trace)

> bundle exec appraisal 4.2 rspec spec/unit/shoulda/matchers/active_record/serialize_matcher_spec.rb 
>> BUNDLE_GEMFILE=/home/jesse/projects/shoulda-matchers/gemfiles/4.2.gemfile bundle exec rspec spec/unit/shoulda/matchers/active_record/serialize_matcher_spec.rb
Could not find rdoc-4.2.0 in any of the sources
Run `bundle install` to install missing gems.
```

`bundle install` always warns me on `nokogiri` and `pg`, and even if I `gem pristine` them it doesn't seem to take hold.

**Comment by mcmire** [comment]
I'm a bit stumped on this, but what if you try this?

```
BUNDLE_GEMFILE=/home/jesse/projects/shoulda-matchers/gemfiles/4.2.gemfile bundle install
```

**Comment by jc00ke** [comment]
1) I think there was an issue with my env (Nix package manager was in the way)
2) after fixing that and making sure to use a Ruby managed by `chruby` I'm still getting strange errors

`Ruby 2.2.2`

```
bundle exec appraisal 4.2 rspec spec/unit/shoulda/matchers/active_record/serialize_matcher_spec.rb
>> BUNDLE_GEMFILE=/home/jesse/projects/shoulda-matchers/gemfiles/4.2.gemfile bundle exec rspec spec/unit/shoulda/matchers/active_record/serialize_matcher_spec.rb
/home/jesse/projects/shoulda-matchers/spec/support/tests/command_runner.rb:112:in `fail!': Command "rails new /home/jesse/projects/shoulda-matchers/tmp/acceptance/test-project --skip-bundle" exited with status 1. (RuntimeError)
Output:
---START----------------------------------------------------------------
/home/jesse/.gem/ruby/2.2.2/gems/bundler-1.9.9/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find rdoc-4.2.0 in any of the sources (Bundler::GemNotFound)
	from /home/jesse/.gem/ruby/2.2.2/gems/bundler-1.9.9/lib/bundler/spec_set.rb:85:in `map!'
	from /home/jesse/.gem/ruby/2.2.2/gems/bundler-1.9.9/lib/bundler/spec_set.rb:85:in `materialize'
	from /home/jesse/.gem/ruby/2.2.2/gems/bundler-1.9.9/lib/bundler/definition.rb:132:in `specs'
	from /home/jesse/.gem/ruby/2.2.2/gems/bundler-1.9.9/lib/bundler/definition.rb:177:in `specs_for'
	from /home/jesse/.gem/ruby/2.2.2/gems/bundler-1.9.9/lib/bundler/definition.rb:166:in `requested_specs'
	from /home/jesse/.gem/ruby/2.2.2/gems/bundler-1.9.9/lib/bundler/environment.rb:18:in `requested_specs'
	from /home/jesse/.gem/ruby/2.2.2/gems/bundler-1.9.9/lib/bundler/runtime.rb:13:in `setup'
	from /home/jesse/.gem/ruby/2.2.2/gems/bundler-1.9.9/lib/bundler.rb:122:in `setup'
	from /home/jesse/.gem/ruby/2.2.2/gems/bundler-1.9.9/lib/bundler/setup.rb:18:in `<top (required)>'
	from /nix/store/2yfwlp0x943cf86i4ccj6arnindqcc2f-ruby-2.1.2-p353/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /nix/store/2yfwlp0x943cf86i4ccj6arnindqcc2f-ruby-2.1.2-p353/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
---END------------------------------------------------------------------

	from /home/jesse/projects/shoulda-matchers/spec/support/tests/command_runner.rb:70:in `block (2 levels) in call'
	from /home/jesse/projects/shoulda-matchers/spec/support/tests/command_runner.rb:180:in `possibly_running_quickly'
	from /home/jesse/projects/shoulda-matchers/spec/support/tests/command_runner.rb:66:in `block in call'
	from /home/jesse/projects/shoulda-matchers/spec/support/tests/command_runner.rb:187:in `possibly_retrying'
	from /home/jesse/projects/shoulda-matchers/spec/support/tests/command_runner.rb:65:in `call'
	from /home/jesse/projects/shoulda-matchers/spec/support/tests/command_runner.rb:11:in `block in run'
	from /home/jesse/projects/shoulda-matchers/spec/support/tests/command_runner.rb:9:in `tap'
	from /home/jesse/projects/shoulda-matchers/spec/support/tests/command_runner.rb:9:in `run'
	from /home/jesse/projects/shoulda-matchers/spec/support/tests/command_runner.rb:16:in `run!'
	from /home/jesse/projects/shoulda-matchers/spec/support/unit/rails_application.rb:123:in `run_command!'
	from /home/jesse/projects/shoulda-matchers/spec/support/unit/rails_application.rb:81:in `rails_new'
	from /home/jesse/projects/shoulda-matchers/spec/support/unit/rails_application.rb:75:in `generate'
	from /home/jesse/projects/shoulda-matchers/spec/support/unit/rails_application.rb:18:in `create'
	from /home/jesse/projects/shoulda-matchers/spec/unit_spec_helper.rb:10:in `<top (required)>'
	from /home/jesse/projects/shoulda-matchers/spec/unit/shoulda/matchers/active_record/serialize_matcher_spec.rb:1:in `require'
	from /home/jesse/projects/shoulda-matchers/spec/unit/shoulda/matchers/active_record/serialize_matcher_spec.rb:1:in `<top (required)>'
	from /home/jesse/.gem/ruby/2.2.2/gems/rspec-core-3.2.0/lib/rspec/core/configuration.rb:1226:in `load'
	from /home/jesse/.gem/ruby/2.2.2/gems/rspec-core-3.2.0/lib/rspec/core/configuration.rb:1226:in `block in load_spec_files'
	from /home/jesse/.gem/ruby/2.2.2/gems/rspec-core-3.2.0/lib/rspec/core/configuration.rb:1224:in `each'
	from /home/jesse/.gem/ruby/2.2.2/gems/rspec-core-3.2.0/lib/rspec/core/configuration.rb:1224:in `load_spec_files'
	from /home/jesse/.gem/ruby/2.2.2/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:97:in `setup'
	from /home/jesse/.gem/ruby/2.2.2/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:85:in `run'
	from /home/jesse/.gem/ruby/2.2.2/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:70:in `run'
	from /home/jesse/.gem/ruby/2.2.2/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:38:in `invoke'
	from /home/jesse/.gem/ruby/2.2.2/gems/rspec-core-3.2.0/exe/rspec:4:in `<top (required)>'
	from /home/jesse/.gem/ruby/2.2.2/bin/rspec:23:in `load'
	from /home/jesse/.gem/ruby/2.2.2/bin/rspec:23:in `<main>'

```

`Ruby 2.1.5`

```
bundle exec appraisal 4.2 rspec spec/unit/shoulda/matchers/active_record/serialize_matcher_spec.rb
>> BUNDLE_GEMFILE=/home/jesse/projects/shoulda-matchers/gemfiles/4.2.gemfile bundle exec rspec spec/unit/shoulda/matchers/active_record/serialize_matcher_spec.rb
Could not find json-1.8.2 in any of the sources
Run `bundle install` to install missing gems.
```

After I did `BUNDLE_GEMFILE=/home/jesse/projects/shoulda-matchers/gemfiles/4.2.gemfile bundle install` and then `bundle exec appraisal 4.2 rspec spec/unit/shoulda/matchers/active_record/serialize_matcher_spec.rb` on `2.1.5` the specs ran.

I did the same thing after switching to `2.2.2` and the specs still don't run. :cry:

**Comment by mcmire** [comment]
Hi @jc00ke, did you ever have any luck with this?

**Comment by jc00ke** [comment]
Looks like it works on `master` now. Not sure what changed, but glad to see it's "fixed".

**Comment by mcmire** [comment]
Okay... strange!
