### ISSUE TITLE
validate_presence_of does not work in an internal object association in 2.8.0

### ISSUE THREAD

**Issue by alexbrahastoll** [thoughtbot/shoulda-matchers#765]
Hello,

I have been trying to use the `validate_presence_of` to check for the presence of an association in an internal object (to whom the wrapping object delegates the get and set messages), but I keep getting a `NoMethodError: undefined method 'each' for nil:NilClass` error.

Here is what I have:

```ruby
class Project < ActiveRecord::Base
  has_and_belongs_to_many :students

  # The rest of the class is omitted for the sake of brevity.
end
```

```ruby
class ProjectBuilder::SelectStudentsStep
  include ActiveModel::Model

  attr_accessor :project
  delegate :students, :students=, to: :project

  validates :students, presence: true
end
```

```ruby
require 'rails_helper'

RSpec.describe ProjectBuilder::SelectStudentsStep, type: :model do
  describe 'validations' do
    subject { ProjectBuilder::SelectStudentsStep.new(project: create(:project)) }
    it { should validate_presence_of(:students) }
  end
end
```

And here is the stack trace:

```
NoMethodError:
       undefined method `each' for nil:NilClass
     # /Users/alexbrahastoll/.rvm/gems/ruby-2.2.2@lumiar/gems/activerecord-4.2.2/lib/active_record/associations/collection_association.rb:365:in `replace'
     # /Users/alexbrahastoll/.rvm/gems/ruby-2.2.2@lumiar/gems/activerecord-4.2.2/lib/active_record/associations/collection_association.rb:47:in `writer'
     # /Users/alexbrahastoll/.rvm/gems/ruby-2.2.2@lumiar/gems/activerecord-4.2.2/lib/active_record/associations/builder/association.rb:123:in `students='
     # ./app/models/project_builder/select_students_step.rb:5:in `students='
     # /Users/alexbrahastoll/.rvm/gems/ruby-2.2.2@lumiar/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:259:in `set_attribute_ignoring_range_errors'
     # /Users/alexbrahastoll/.rvm/gems/ruby-2.2.2@lumiar/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:254:in `set_attribute'
     # /Users/alexbrahastoll/.rvm/gems/ruby-2.2.2@lumiar/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:223:in `block in matches?'
     # /Users/alexbrahastoll/.rvm/gems/ruby-2.2.2@lumiar/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:220:in `each'
     # /Users/alexbrahastoll/.rvm/gems/ruby-2.2.2@lumiar/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:220:in `none?'
     # /Users/alexbrahastoll/.rvm/gems/ruby-2.2.2@lumiar/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:220:in `matches?'
     # /Users/alexbrahastoll/.rvm/gems/ruby-2.2.2@lumiar/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/disallow_value_matcher.rb:16:in `matches?'
     # /Users/alexbrahastoll/.rvm/gems/ruby-2.2.2@lumiar/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/validation_matcher.rb:56:in `disallows_value_of'
     # /Users/alexbrahastoll/.rvm/gems/ruby-2.2.2@lumiar/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/validate_presence_of_matcher.rb:126:in `matches?'
     # ./spec/models/project_builder/select_students_step_spec.rb:6:in `block (3 levels) in <top (required)>'
```

I can get and set students in a Project object via a ProjectBuilder::SelectStudentsStep object just fine in a rails console (and the rails presence validation is also working correctly).

I am using ruby 2.2.2, rails 4.2.2 and shoulda-matchers 2.8.0

Is this a supported use case? Am I doing something wrong here?

Thanks in advance!

**Comment by mcmire** [comment]
In short, `validate_presence_of` doesn't support associations just yet.

`validate_presence_of` works by setting the attribute in question to nil. I don't think that an association can be set to nil. It can be set to an empty array or cleared, but not to nil. So that's why you're getting that error.

**Comment by maurogeorge** [comment]
@mcmire @alexbrahastoll  I think we can close this in favor of https://github.com/thoughtbot/shoulda-matchers/issues/535 makes sense to you?

**Comment by maurogeorge** [comment]
Sorry guys, the #535 is about `validates_uniqueness_of` and not `validate_presence_of`.

I take a look on the code and `validate_presence_of` handle presence of associations as you can see [here](https://github.com/thoughtbot/shoulda-matchers/blob/a3fb06c369c2b5e96831cb2c6c8532de8e2f0e62/spec/unit/shoulda/matchers/active_model/validate_presence_of_matcher_spec.rb#L42-L53).

I send a PR to fix this https://github.com/thoughtbot/shoulda-matchers/pull/767 please take a look, I added more info in the PR.

**Comment by mcmire** [comment]
Closing this in favor of #767.
