### ISSUE TITLE
"can't dup Symbol" in active_model/helpers.rb:8

### ISSUE THREAD

**Issue by JasonBarnabe** [thoughtbot/shoulda-matchers#766]
Ruby 2.0.0-p643, Rails 4.0.13, shoulda-matchers 2.8.0.

I have a model that does this:

``` ruby
  def errors
    err = super
    if address && address.errors.present?
      err.set(:address, address.errors)
    end
    err
  end
```

In the spec for the model I do this:

``` ruby
    [:patient_id, :full_name, :address, :payment_type].each do |attrib|
      it { should validate_presence_of(attrib) }
    end
```

This results in:

```
  1) PaymentMethod Attributes should require patient_id to be set
     Failure/Error: it { should validate_presence_of(attrib) }
     TypeError:
       can't dup Symbol
     # /Users/jason/.rvm/gems/ruby-2.0.0-p643/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/helpers.rb:8:in `dup'
     # /Users/jason/.rvm/gems/ruby-2.0.0-p643/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/helpers.rb:8:in `block in pretty_error_messages'
     # /Users/jason/.rvm/gems/ruby-2.0.0-p643/gems/activemodel-4.0.13/lib/active_model/errors.rb:162:in `block (2 levels) in each'
     # /Users/jason/.rvm/gems/ruby-2.0.0-p643/gems/activemodel-4.0.13/lib/active_model/errors.rb:162:in `block (2 levels) in each'
     # /Users/jason/.rvm/gems/ruby-2.0.0-p643/gems/activemodel-4.0.13/lib/active_model/errors.rb:162:in `each'
     # /Users/jason/.rvm/gems/ruby-2.0.0-p643/gems/activemodel-4.0.13/lib/active_model/errors.rb:162:in `block in each'
     # /Users/jason/.rvm/gems/ruby-2.0.0-p643/gems/activemodel-4.0.13/lib/active_model/errors.rb:161:in `each_key'
     # /Users/jason/.rvm/gems/ruby-2.0.0-p643/gems/activemodel-4.0.13/lib/active_model/errors.rb:161:in `each'
     # /Users/jason/.rvm/gems/ruby-2.0.0-p643/gems/activemodel-4.0.13/lib/active_model/errors.rb:162:in `block in each'
     # /Users/jason/.rvm/gems/ruby-2.0.0-p643/gems/activemodel-4.0.13/lib/active_model/errors.rb:161:in `each_key'
     # /Users/jason/.rvm/gems/ruby-2.0.0-p643/gems/activemodel-4.0.13/lib/active_model/errors.rb:161:in `each'
     # /Users/jason/.rvm/gems/ruby-2.0.0-p643/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/helpers.rb:7:in `map'
     # /Users/jason/.rvm/gems/ruby-2.0.0-p643/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/helpers.rb:7:in `pretty_error_messages'
     # /Users/jason/.rvm/gems/ruby-2.0.0-p643/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/validator.rb:53:in `messages_description'
     # /Users/jason/.rvm/gems/ruby-2.0.0-p643/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:322:in `error_description'
     # /Users/jason/.rvm/gems/ruby-2.0.0-p643/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:229:in `failure_message'
     # /Users/jason/.rvm/gems/ruby-2.0.0-p643/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/disallow_value_matcher.rb:40:in `failure_message_when_negated'
     # /Users/jason/.rvm/gems/ruby-2.0.0-p643/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/validation_matcher.rb:57:in `disallows_value_of'
     # /Users/jason/.rvm/gems/ruby-2.0.0-p643/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/validate_presence_of_matcher.rb:126:in `matches?'
     # ./spec/models/payment_method_spec.rb:10:in `block (4 levels) in <top (required)>'
```

**Comment by mcmire** [comment]
First of all, it's probably better to assign errors in a validation rather than overriding #errors.

Secondly, ActiveModel::Errors is basically a hash of attribute names to string messages; a value cannot be another instance of Errors. You probably want something more like this instead:

``` ruby
def errors
  super.tap do |errors|
    if address && address.errors.present?
      address.errors.each do |attr, message|
        errors.add :base, "#{attr.to_s.humanize} #{message[0].downcase + message[1..1]}"
      end
    end
  end
end
```

**Comment by JasonBarnabe** [comment]
Well, this is some code written by someone else and seemingly works with the views and everything else, and only became a problem after upgrading shoulda-matchers. I figured the scenario was a little weird, but also the fix seems like it'd be simple - don't `dup` if it's a symbol. I leave it up to you if you care to handle this.

**Comment by mcmire** [comment]
Okay... after taking another look at ActiveModel::Errors, it does look like it technically allows another Errors object to be embedded like this. So to properly fix this issue, our `pretty_error_messages` method (which is our helper method that spits out the full error messages for a record) needs to be recursive.

I'll keep this open.

**Comment by mcmire** [comment]
In the meantime, you can use `allow_value`:

``` ruby
it { should_not allow_value(nil).for(:address) }
```

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
