### ISSUE TITLE
validates_numericality_of with only_integer: true raises CouldNotSetAttributeError

### ISSUE THREAD

**Issue by lowjoel** [thoughtbot/shoulda-matchers#801]
My spec, from Coursemology/coursemology2, spec/models/course/experience_points_record_spec.rb
```ruby
RSpec.describe Course::ExperiencePointsRecord do
  # snip
  it { is_expected.to validate_numericality_of(:points_awarded).only_integer }
  # snip
```

This used to pass with 2.x, upgrading to 3.0 gives me this:
```
Shoulda::Matchers::ActiveModel::AllowValueMatcher::CouldNotSetAttributeError: Expected Class to be able to set points_awarded to "abcd", but got 0 instead.
./vendor/bundle/ruby/2.2.0/gems/shoulda-matchers-3.0.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:440:in `ensure_that_attribute_was_set!'
./vendor/bundle/ruby/2.2.0/gems/shoulda-matchers-3.0.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:432:in `set_attribute'
./vendor/bundle/ruby/2.2.0/gems/shoulda-matchers-3.0.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:426:in `value_matches?'
./vendor/bundle/ruby/2.2.0/gems/shoulda-matchers-3.0.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:384:in `block in matches?'
./vendor/bundle/ruby/2.2.0/gems/shoulda-matchers-3.0.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:384:in `each'
./vendor/bundle/ruby/2.2.0/gems/shoulda-matchers-3.0.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:384:in `all?'
./vendor/bundle/ruby/2.2.0/gems/shoulda-matchers-3.0.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:384:in `matches?'
./vendor/bundle/ruby/2.2.0/gems/shoulda-matchers-3.0.0/lib/shoulda/matchers/active_model/disallow_value_matcher.rb:16:in `matches?'
./vendor/bundle/ruby/2.2.0/gems/shoulda-matchers-3.0.0/lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb:453:in `block in first_failing_submatcher'
./vendor/bundle/ruby/2.2.0/gems/shoulda-matchers-3.0.0/lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb:452:in `each'
./vendor/bundle/ruby/2.2.0/gems/shoulda-matchers-3.0.0/lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb:452:in `detect'
./vendor/bundle/ruby/2.2.0/gems/shoulda-matchers-3.0.0/lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb:452:in `first_failing_submatcher'
./vendor/bundle/ruby/2.2.0/gems/shoulda-matchers-3.0.0/lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb:394:in `matches?'
./vendor/bundle/ruby/2.2.0/gems/rspec-expectations-3.3.1/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
./vendor/bundle/ruby/2.2.0/gems/rspec-expectations-3.3.1/lib/rspec/expectations/handler.rb:27:in `with_matcher'
./vendor/bundle/ruby/2.2.0/gems/rspec-expectations-3.3.1/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
./vendor/bundle/ruby/2.2.0/gems/rspec-expectations-3.3.1/lib/rspec/expectations/expectation_target.rb:54:in `to'
./spec/models/course/experience_points_record_spec.rb:6:in `block (2 levels) in <top (required)>'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:206:in `instance_exec'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:206:in `block in run'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:430:in `block in with_around_and_singleton_context_hooks'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:388:in `block in with_around_example_hooks'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:478:in `block in run'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:618:in `block in run_around_example_hooks_for'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:273:in `call'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:273:in `call'
./vendor/bundle/ruby/2.2.0/bundler/gems/bullet-e60794cc802b/lib/bullet.rb:188:in `profile'
./spec/support/bullet.rb:6:in `block in extended'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:378:in `instance_exec'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:378:in `instance_exec'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:389:in `execute_with'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:620:in `block (2 levels) in run_around_example_hooks_for'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:273:in `call'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:273:in `call'
./vendor/bundle/ruby/2.2.0/gems/rspec-rails-3.3.3/lib/rspec/rails/adapters.rb:127:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:378:in `instance_exec'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:378:in `instance_exec'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:389:in `execute_with'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:620:in `block (2 levels) in run_around_example_hooks_for'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:273:in `call'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:273:in `call'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:621:in `run_around_example_hooks_for'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:478:in `run'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:388:in `with_around_example_hooks'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:430:in `with_around_and_singleton_context_hooks'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:203:in `run'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:559:in `block in run_examples'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:555:in `map'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:555:in `run_examples'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:521:in `run'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115:in `block (3 levels) in run_specs'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115:in `map'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115:in `block (2 levels) in run_specs'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1627:in `with_suite_hooks'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:114:in `block in run_specs'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/reporter.rb:77:in `report'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:113:in `run_specs'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:89:in `run'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73:in `run'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:41:in `invoke'
./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/exe/rspec:4:in `<top (required)>'
./vendor/bundle/ruby/2.2.0/bin/rspec:23:in `load'
./vendor/bundle/ruby/2.2.0/bin/rspec:23:in `<top (required)>'
```

Any ideas? Thanks!

**Comment by mcmire** [comment]
Yup, this will be fixed in 3.0.1 (the fix was made in 18b2859d2522a4866c398b9a32ebc3de4ec79389).

**Comment by lowjoel** [comment]
Thanks!

**Comment by chrisokamoto** [comment]
This error is happening with me but I couldn't file version 3.0.1 in Gem. I'm using 3.0.0

**Comment by greysteil** [comment]
@mcmire - any chance of a 3.0.1 soon? Keen to move to 3.0, but this is blocking us.

**Comment by mcmire** [comment]
@greysteil I just released 3.0.1 which should fix this particular issue.

**Comment by chrisokamoto** [comment]
It seems that there are bugs yet with "only_integer" validation... In shoulda-matchers 2.8.0 all tests were passing.. now, with 3.0.0 and even with 3.0.1 I keep getting the error above:

"Failure/Error: it { is_expected.to validate_numericality_of(:tamanho).only_integer }
     Shoulda::Matchers::ActiveModel::AllowValueMatcher::CouldNotSetAttributeError:
       The allow_value matcher attempted to set :size on Widget to 0.1, but
       when the attribute was read back, it had stored 0 instead.
       
       This creates a problem because it means that the model is behaving in a
       way that is interfering with the test -- there's a mismatch between the
       test that was written and test that was actually run.
       
       There are a couple of reasons why this could be happening:
       
       * The writer method for :size has been overridden and contains
         custom logic to prevent certain values from being set or change which
         values are stored.
       * ActiveRecord is typecasting the incoming value.
       
       Regardless, the fact you're seeing this message usually indicates a
       larger problem. Please file an issue on the GitHub repo for
       shoulda-matchers, including details about your model and the test
       you've written, and we can point you in the right direction:
       
       https://github.com/thoughtbot/shoulda-matchers/issues
"

**Comment by mcmire** [comment]
@chrisokamoto Integer columns, by definition, typecast all of their incoming values to integers. By using `only_integer`, you're telling the matcher, "if this attribute is set a float, then it should be invalid". But this test is impossible to write, because as soon as you set the attribute to a float, it turns into an integer. What this means is that using a numericality validation with `only_integer` isn't actually necessary because that validation would never fail. The column is already guaranteed to be an integer -- it can't be anything but. So you can get rid of both that validation and the matcher. Does that make sense?

**Comment by chrisokamoto** [comment]
Yes, it does.. Thanks!!

**Comment by pixeltrix** [comment]
@mcmire I think you're misunderstanding the point of `validates_numericality_of only_integer: true`. The validation is there to provide feedback to the user that fractional values are invalid and won't work rather than just blindly converting to an integer and saving. The validator itself works on the raw value and not the type casted value. I suspect this will be biting a lot of people when they upgrade.

**Comment by mcmire** [comment]
> The validator itself works on the raw value and not the type casted value

Right, I had no clue this was the case until I started looking into this issue, I assumed it wasn't smart enough to do that. This is definitely an oversight on my part. I'll fix it in the next imminent release.

**Comment by pixeltrix** [comment]
@mcmire thanks
