### ISSUE TITLE
Using the route matcher with 'format' can lead to failing specs, while everything is correct

### ISSUE THREAD

**Issue by aried3r** [thoughtbot/shoulda-matchers#809]
When having a route, or namespace like this:

``` Ruby
namespace :api, defaults: { format: 'json' } do
  # some routes
end
```

and trying to assert this behavior using the `route` shoulda-matcher

``` Ruby
it { is_expected.to route(:get, '/api/projects/1').to(action: :show, id: 1, format: :json) }
```

the spec will fail with something like:

``` diff
The recognized options <{"controller"=>"projects", "action"=>"show", "id"=>"1", "format"=>"json"}> did not match <{"action"=>"show", "id"=>"1", "format"=>:json, "controller"=>"projects"}>, difference:.
--- expected
+++ actual
@@ -1 +1 @@
-{"action"=>"show", "id"=>"1", "format"=>:json, "controller"=>"projects"}
+{"controller"=>"projects", "action"=>"show", "id"=>"1", "format"=>"json"}
```

because the matcher will try to match the symbol (spec) against a string (`route.rb`).

See https://github.com/thoughtbot/shoulda-matchers/pull/693 for more details.

**Comment by thalesfp** [comment]
:+1:

**Comment by istana** [comment]
I have the same problem. I thought I can fix it with `format: 'json'` instead of `format: :json` in the spec, but no - it is still treated as symbol.

**Comment by dolzenko** [comment]
This seems to be introduced by https://github.com/thoughtbot/shoulda-matchers/commit/15359eb6ec4f99acd9b970d7129edc641ad68b57. I can't see where the format being a symbol requirement is documented, should we revert that commit? /cc @maurogeorge

**Comment by mcmire** [comment]
I think you're right, and I would agree that we should not be symbolizing the `format` -- in fact, we shouldn't even be changing it in any way.

**Comment by lfzawacki** [comment]
+1 I'm affected by the same problem. Tests are being skipped while waiting for a solution.

**Comment by dolzenko** [comment]
For those waiting for fix - just put this

```ruby
Shoulda::Matchers::ActionController::RouteParams::PARAMS_TO_SYMBOLIZE = []
```

into `spec_helper.rb`. That worked for me.

**Comment by aried3r** [comment]
If that works, would that be sufficient for a pull request?

**Comment by dolzenko** [comment]
@aried3r no, the whole thing is useless then https://github.com/thoughtbot/shoulda-matchers/blob/8253d4b4c9b5489ea003784e638e04db353f6250/lib/shoulda/matchers/action_controller/route_params.rb#L6

**Comment by aried3r** [comment]
That's what I meant, can we remove it and be good?

**Comment by mcmire** [comment]
You might try:

``` ruby
Shoulda::Matchers::ActionController::RouteParams.class_eval do
  def symbolize_or_stringify(key, value)
    if key.in?(PARAMS_TO_SYMBOLIZE)
      value
    else
      stringify(value)
    end
  end
end
```

**Comment by zw963** [comment]
Hi, I work on a new team, this team still use rails 4.1.16.

I got follow error:

```rb
# config/routes
namespace :dingding_crm, defaults: { format: :json } do
        resources :specialists, only: [:show]
      end
end
```
Following spec is failed

```rb
require 'rails_helper'

RSpec.describe Api::DingdingCrm::SpecialistsController, type: :controller do
  it '' do
    should route(:get, 'api/dingding_crm/specialists/100')
      .to(action: :show, id: 100, format: :json)
  end
end
```

Error logs:

```diff
     Failure/Error: should route(:get, 'api/dingding_crm/specialists/100')
       The recognized options <{"format"=>:json, "action"=>"show", "controller"=>"api/dingding_crm/specialists", "id"=>"100"}> did not match <{"action"=>"show", "id"=>"100", "format"=>"json", "controller"=>"api/dingding_crm/specialists"}>, difference:.
       --- expected
       +++ actual
       @@ -1 +1 @@
       -{"action"=>"show", "id"=>"100", "format"=>"json", "controller"=>"api/dingding_crm/specialists"}
       +{"format"=>:json, "action"=>"show", "controller"=>"api/dingding_crm/specialists", "id"=>"100"}
```

I have to workaround this with change `routes.rb` to:
```rb
namespace :dingding_crm, defaults: { format: 'json' } do
        resources :specialists, only: [:show]
      end
end
```

This is worked again.

so, this issue still exists, right?

following is version:
```sh
 ╰─ $ 1  bundle list |grep shoulda
  * shoulda (3.5.0)
  * shoulda-context (1.2.2)
  * shoulda-matchers (2.8.0)
```

**Comment by mcmire** [comment]
@zw963 You're using an older version of shoulda-matchers, it looks like. What happens if you upgrade to 3.1.2?

**Comment by zw963** [comment]
@mcmire , hi, I have to development on a very old project (rails 4.1.16)

I only add 
```rb
  gem 'shoulda'
  gem 'shoulda-matchers'
```
into Gemfile in recent days, those version seem like is the suitable version manage by bundler.

**Comment by mcmire** [comment]
@zw963 We do still support Rails 4.1, but I guess upgrading wouldn't help in this case, so I'm not sure why I said that :) I thought I had fixed this problem somewhere along the way but I guess I haven't yet. Sorry about that. Your "fix" to routes.rb seems like the right move.

**Comment by zw963** [comment]
@mcmire , so, there is no plan to try fix this for Rails 4.1, right ?

**Comment by mcmire** [comment]
@zw963 If it only shows up under Rails 4.1, then we won't be addressing it, but, I'm thinking that this problem may exist under other Rails versions, and if that's the case, then you would get this fix for free.

**Comment by istana** [comment]
AFAIK it hasn't been fixed yet. And probably never will be as there is a ton of PRs and no activity in repository.

**Comment by mcmire** [comment]
@istana Hey, I don't really appreciate your comments. Let's try to keep it civil around here. Thanks.

**Comment by zw963** [comment]
@mcmire , I tried in my another project, which is `rails 5.1.1`

Following is my route:
```rb
namespace :wx_mini_api, path: '' do
  namespace :v1, defaults: {format: :json} do
    resources :items, only: [:show, :index]
  end
end
```

Following is my test: (minitest)

```rb
class WxMiniApi::V1::ItemsControllerTest < ActionDispatch::IntegrationTest
  should route(get: 'items').to(action: :index, format: :json)
end
```

But I got following error:

```sh
 ╰─ $ 1  rails test /home/zw963/Xthink/ershou_web/test/controllers/wx_mini_api/v1/items_controller_test.rb
Running via Spring preloader in process 27342
/home/zw963/Xthink/ershou_web/test/controllers/wx_mini_api/v1/items_controller_test.rb:4:in `<class:ItemsControllerTest>': undefined method `route' for WxMiniApi::V1::ItemsControllerTest:Class (NoMethodError)
	from /home/zw963/Xthink/ershou_web/test/controllers/wx_mini_api/v1/items_controller_test.rb:3:in `<top (required)>'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `block in require'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/railties-5.1.1/lib/rails/test_unit/test_requirer.rb:14:in `block in require_files'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/railties-5.1.1/lib/rails/test_unit/test_requirer.rb:13:in `each'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/railties-5.1.1/lib/rails/test_unit/test_requirer.rb:13:in `require_files'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/railties-5.1.1/lib/rails/test_unit/minitest_plugin.rb:96:in `plugin_rails_init'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/minitest-5.10.3/lib/minitest.rb:81:in `block in init_plugins'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/minitest-5.10.3/lib/minitest.rb:79:in `each'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/minitest-5.10.3/lib/minitest.rb:79:in `init_plugins'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/minitest-5.10.3/lib/minitest.rb:130:in `run'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/railties-5.1.1/lib/rails/test_unit/minitest_plugin.rb:77:in `run'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/minitest-5.10.3/lib/minitest.rb:63:in `block in autorun'
	from /home/zw963/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/zw963/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

Following is shoulda version.
```sh
 ╰─ $ bundle list |grep shoulda
  * shoulda (3.5.0)
  * shoulda-context (1.2.2)
  * shoulda-matchers (2.8.0)
```

**Comment by mcmire** [comment]
@zw963 Sigh... I'm sorry. `shoulda` has a dependency on `shoulda-matchers` 2.8.0 right now so that's what version it will use. I really need to address this. Does your project really use Minitest or can you use RSpec?

**Comment by zw963** [comment]
@mcmire，I don't understood what you means，this new rails 5.1.1 i use minitest.

**Comment by istana** [comment]
@mcmire I'm sorry for my reaction. I really appreciate the work you do here.

In my case it didn't work in Rails 4.2 either, but with shoulda matchers 2.8.0. I could try to trigger the bug with latest Rails 5.1 and shoulda matchers.

**Comment by philihp** [comment]
Fixed this by just changing my routes.

```ruby
  namespace :api, defaults: { format: 'json' } do
```
to
```ruby
  namespace :api, defaults: { format: :json } do
```

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
