### ISSUE TITLE
Uniqueness validation spec examples started failing after upgrading from 2.8.0 to 3.0.1 

### ISSUE THREAD

**Issue by jiggneshhgohel** [thoughtbot/shoulda-matchers#853]
I have updated shoulda-matchers from 2.8.0 to 3.0.1 and suddenly the uniqueness validation spec examples in few of my model specs have started failing. Showing below details for one of such model:

**Versions**

Rails 4.2.0
ruby-2.2.1 [ x86_64 ]
gem 'shoulda-matchers', '~> 3.0'

**Model**

```
class Device < ActiveRecord::Base
  validates_presence_of :uuid, :manufacturer
  validates_uniqueness_of :uuid, message: "UUID is already allocated to some other Device", case_sensitive: false
end
```

**Model spec**

```
require 'rails_helper'

RSpec.describe Device, type: :model do
  it { should respond_to(:uuid) }
  it { should respond_to(:manufacturer) }

  it { should validate_presence_of(:uuid) }
  it { should validate_presence_of(:manufacturer) }

  context "uniqueness validation" do
    subject { build(:device)  }

    it {
      should validate_uniqueness_of(:uuid).with_message('UUID is already assigned to some other Device').case_insensitive
    }
  end
end
```

**Factory definition**

```
FactoryGirl.define do
  ....

  factory(:device) do
    uuid         { SecureRandom.hex(7) }
    manufacturer "Test Manufacturer"
  end
end
```

**Spec run output**

```
Beacon
  should respond to #uuid
  should respond to #manufacturer
  should require uuid to be set
  should require manufacturer to be set
  uniqueness validation
>>>>>>>>> #<Device id: nil, uuid: "ba2954921d4e75", manufacturer: "Test Manufacturer", created_at: nil, updated_at: nil>
    should require unique value for uuid (FAILED - 1)

Failures:

  1) Device uniqueness validation should require unique value for uuid
     Failure/Error: should validate_uniqueness_of(:uuid).with_message('UUID is already assigned to some other Device').case_insensitive

       Expected errors to include "UUID is already assigned to some other Device" when uuid is set to "a",
       got errors:
       * "can't be blank" (attribute: manufacturer, value: "")
       * "UUID is already allocated to some other Device" (attribute: uuid, value: "a")
     # ./spec/models/device_spec.rb:20:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:61:in `block (3 levels) in <top (required)>'
     # /home/jignesh/.rvm/gems/ruby-2.2.1@myapp/gems/database_cleaner-1.5.1/lib/database_cleaner/generic/base.rb:16:in `cleaning'
     # /home/jignesh/.rvm/gems/ruby-2.2.1@myapp/gems/database_cleaner-1.5.1/lib/database_cleaner/base.rb:92:in `cleaning'
     # /home/jignesh/.rvm/gems/ruby-2.2.1@myapp/gems/database_cleaner-1.5.1/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # /home/jignesh/.rvm/gems/ruby-2.2.1@myapp/gems/database_cleaner-1.5.1/lib/database_cleaner/configuration.rb:87:in `call'
     # /home/jignesh/.rvm/gems/ruby-2.2.1@myapp/gems/database_cleaner-1.5.1/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/rails_helper.rb:60:in `block (2 levels) in <top (required)>'

Finished in 3.86 seconds (files took 1.47 seconds to load)
9 examples, 1 failure

Failed examples:

rspec ./spec/models/device_spec.rb:17 # Device uniqueness validation should require unique value for uuid
```

The strange thing is I inspected the subject Device instance and the :device factory definition does sets manufacturer. Despite this the error contains _manufacturer can't be blank_ error:
- "can't be blank" (attribute: manufacturer, value: "")
- "UUID is already allocated to some other Device" (attribute: uuid, value: "a")

Can someone please confirm is this a bug or I am doing something wrong?

Thanks.

**Comment by mcmire** [comment]
The way the matcher works is that it takes the subject, ensures it's saved, and then makes a new record from the model you're using and makes assertions on that new record. `manufacturer` will not be set on this new record.

It's a bug, and we've run into it before, although I can't find the exact issue. Related issues are #778 and #567.

**Comment by mcmire** [comment]
Revisiting this (super old, I know) issue. I think all this was was a difference in error messages: "UUID is already assigned to some other Device" vs. "UUID is already _allocated_ to some other Device". Closing.
