### ISSUE TITLE
validate_numericality_of only_integer with Postgresql Integer column type

### ISSUE THREAD

**Issue by mareczek** [thoughtbot/shoulda-matchers#872]
Model:
```ruby
# == Schema Information
#
# Table name: events
#
#  id                   :uuid             not null, primary key
#  default_shift_length :integer

class Event < ActiveRecord::Base
  validates :default_shift_length,
    presence: true,
    numericality: {
      only_integer: true,
      greater_than: 0,
      less_than_or_equal_to: 23
    }
end
```

RSpec:
```ruby
    it { should validate_numericality_of(:default_shift_length).is_greater_than(0).is_less_than_or_equal_to(23).only_integer }
```

RSpec output:
```bash
Failures:

  1) Event ActiveModel validations should only allow integers for default_shift_length which are greater than 0 and less than or equal to 23
     Failure/Error: it { should validate_numericality_of(:default_shift_length).is_greater_than(0).is_less_than_or_equal_to(23).only_integer }
     
     Shoulda::Matchers::ActiveModel::AllowValueMatcher::CouldNotSetAttributeError:
       The allow_value matcher attempted to set :default_shift_length on Event
       to 0.1, but when the attribute was read back, it had stored 0 instead.
     
       This creates a problem because it means that the model is behaving in a
       way that is interfering with the test -- there's a mismatch between the
       test that was written and test that was actually run.
     
       There are a couple of reasons why this could be happening:
     
       * The writer method for :default_shift_length has been overridden and
         contains custom logic to prevent certain values from being set or
         change which values are stored.
       * ActiveRecord is typecasting the incoming value.
     
       Regardless, the fact you're seeing this message usually indicates a
       larger problem. Please file an issue on the GitHub repo for
       shoulda-matchers, including details about your model and the test
       you've written, and we can point you in the right direction:
     
       https://github.com/thoughtbot/shoulda-matchers/issues
     # ./spec/models/event_spec.rb:38:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:32:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:31:in `block (2 levels) in <top (required)>'
     # -e:1:in `<main>'
```

**Comment by mcmire** [comment]
Thanks. This is a change that was introduced in 3.0, and I'm working on a way to revert it. Unfortunately, there isn't a workaround right now, aside from not using `only_integer`.

**Comment by mareczek** [comment]
Cool thanks, at the moment I'm just skipping this example and have another one without 'only_integer'

**Comment by mcmire** [comment]
@mareczek This should now be fixed. Would you be willing to point to master in your app's Gemfile and see if that fixes the tests that were failing?

**Comment by mareczek** [comment]
@mcmire yup, confirmed. Works
