### ISSUE TITLE
undefined method `permit' when running controller specs

### ISSUE THREAD

**Issue by jerryjohnjacob** [thoughtbot/shoulda-matchers#900]
I've updated shoulda-matchers from version 2.8.0 to 3.1.1.

Getting the following error now for specs which were **previously passing**:

     AdjustmentsController#create
     Failure/Error:
       is_expected.to permit(
         :amount,
         :time_of_transaction,
         :description,
         :type).for :create, params: { loan_id: loan.id }

     NoMethodError:
       undefined method `permit' for #<RSpec::ExampleGroups::AdjustmentsController::Create:0x00000005559790>
     # /home/vagrant/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.1/lib/action_dispatch/testing/assertions/routing.rb:171:in `method_missing'
     # ./spec/controllers/adjustments_controller_spec.rb:20:in `block (3 levels) in <top (required)>'

Here's the spec itself:

    it do
      is_expected.to permit(
        :amount,
        :time_of_transaction,
        :description,
        :type).for :create, params: { loan_id: loan.id }
    end

Has the `permit` matcher been changed?

**Comment by jerryjohnjacob** [comment]
Actually, just managed to fix it. Looks like there are configurations required for the new version. Adding the following to `rails_helper` helped resolve the issue:

    Shoulda::Matchers.configure do |config|
      config.integrate do |with|
        with.test_framework :rspec
        with.library :rails
      end
    end

**Comment by jerryjohnjacob** [comment]
In case anyone else faced the issue and is wondering, [here's why](https://robots.thoughtbot.com/shoulda-matchers-3-0#an-aside-why-did-the-installation-instructions-change).
