### ISSUE TITLE
Possible bug in route matcher

### ISSUE THREAD

**Issue by AlexVPopov** [thoughtbot/shoulda-matchers#928]
Given the spec:

```ruby
it { should route(:patch, '/notes/1').to(action: :update, foramt: :json, id: 1)
```

I get the following error:

```ruby
should route PATCH /notes/1 to/from {:action=>"update", :foramt=>"json", :id=>"1", :controller=>"v1/notes"} (FAILED - 1)

Failures:

  1) V1::NotesController routing should route PATCH /notes/1 to/from {:action=>"update", :foramt=>"json", :id=>"1", :controller=>"v1/notes"}
     Failure/Error: it { should route(:patch, '/notes/1').to(action: :update, foramt: :json, id: 1) }
     
       The recognized options <{"format"=>:json, "controller"=>"v1/notes", "action"=>"update", "id"=>"1"}> did not match <{"action"=>"update", "foramt"=>"json", "id"=>"1", "controller"=>"v1/notes"}>, difference:.
       --- expected
       +++ actual
       @@ -1 +1 @@
       -{"action"=>"update", "foramt"=>"json", "id"=>"1", "controller"=>"v1/notes"}
       +{"format"=>:json, "controller"=>"v1/notes", "action"=>"update", "id"=>"1"}
     # ./spec/controllers/v1/notes_controller_spec.rb:11:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:45:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:45:in `block (2 levels) in <top (required)>'
     # -e:1:in `<main>'
```

As far as I can see, the only difference is that is expects the value of `format` as a string (`"json"`), but gets it as a symbol (`:json`). The strange thing, though, is I have a couple of other routing specs, which work as expected:

```ruby
it { should route(:post, '/notes').to(action: :create, format: :json) }
it { should route(:get, '/notes/1').to(action: :show, format: :json, id: 1) }
it { should route(:get, '/notes').to(action: :index, format: :json) }
```

so this happens only with patch.

If I remove the json constraint from my routes and from the specs, all the specs pass.

**Comment by AlexVPopov** [comment]
Somehow the problem disappeared.

**Comment by mcmire** [comment]
This has been reported before, so I don't think you were crazy: #928
