### ISSUE TITLE
validate_numericality_of will raise error when compared two columns

### ISSUE THREAD

**Issue by bucket-sven** [thoughtbot/shoulda-matchers#937]
Hello,

I have model like this:

``` ruby
class Edu
   validates_numericality_of :start_year, greater_than_or_equal_to: 1900, allow_nil: true
   validates_numericality_of :end_year, greater_than_or_equal_to: :start_year, less_than_of_equal_to: 3000, allow_nil: true 
end
```

In my spec/models/edu_spec.rb, I wrote:

``` ruby
it { is_expected.to validate_numericality_of(:end_year).is_less_than_or_equal_to(3000) }
```

It will raise the error: 

```
ArgumentError:
       comparison of Float with nil failed
     # ./gems/activemodel-4.2.5/lib/active_model/validations/numericality.rb:58:in `>='
     # ./gems/activemodel-4.2.5/lib/active_model/validations/numericality.rb:58:in `block in validate_each'
     # ./gems/activemodel-4.2.5/lib/active_model/validations/numericality.rb:44:in `each'
     # ./gems/activemodel-4.2.5/lib/active_model/validations/numericality.rb:44:in `validate_each'
     # ./gems/activemodel-4.2.5/lib/active_model/validator.rb:151:in `block in validate'
     # ./gems/activemodel-4.2.5/lib/active_model/validator.rb:148:in `each'
     # ./gems/activemodel-4.2.5/lib/active_model/validator.rb:148:in `validate'
     # .gems/activesupport-4.2.5/lib/active_support/callbacks.rb:455:in `public_send'
     #./gems/activesupport-4.2.5/lib/active_support/callbacks.rb:455:in `block in make_lambda'
     # ./gems/activesupport-4.2.5/lib/active_support/callbacks.rb:192:in `block in simple'
     # ./gems/activesupport-4.2.5/lib/active_support/callbacks.rb:504:in `block in call'
     # ./gems/activesupport-4.2.5/lib/active_support/callbacks.rb:504:in `each'
     # ./gems/activesupport-4.2.5/lib/active_support/callbacks.rb:504:in `call'
     # ./gems/activesupport-4.2.5/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
     # ./gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_validate_callbacks'
     # ./gems/activemodel-4.2.5/lib/active_model/validations.rb:398:in `run_validations!'
     # ./gems/activemodel-4.2.5/lib/active_model/validations/callbacks.rb:113:in `block in run_validations!'
     # ./gems/activesupport-4.2.5/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
     # ./gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_validation_callbacks'
     # ./gems/activemodel-4.2.5/lib/active_model/validations/callbacks.rb:113:in `run_validations!'
     # ./gems/activemodel-4.2.5/lib/active_model/validations.rb:337:in `valid?'
     # ./gems/activerecord-4.2.5/lib/active_record/validations.rb:58:in `valid?'
     # ./gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/validator.rb:97:in `validation_errors'
     # ./gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/validator.rb:77:in `collect_messages'
     # ./gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/validator.rb:40:in `messages'
     # ./gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/validator.rb:48:in `has_messages?'
     # ./gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:277:in `has_messages?'
     # ./gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:273:in `errors_match?'
     # ./gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:224:in `block in matches?'
     # ./gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:220:in `each'
     # ./gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:220:in `none?'
     # ./gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:220:in `matches?'
     # ./gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/numericality_matchers/comparison_matcher.rb:83:in `block in submatchers_and_results'
     # ./gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/numericality_matchers/comparison_matcher.rb:82:in `map'
     # ./gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/numericality_matchers/comparison_matcher.rb:82:in `submatchers_and_results'
     # ./gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/numericality_matchers/comparison_matcher.rb:62:in `failing_submatchers'
     # ./gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/numericality_matchers/comparison_matcher.rb:58:in `all_bounds_correct?'
     # ./gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/numericality_matchers/comparison_matcher.rb:34:in `matches?'
     # ./gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb:409:in `block in submatchers_and_results'
     # ./gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb:408:in `map'
     # ./gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb:408:in `submatchers_and_results'
     # ./gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb:414:in `failing_submatchers'
     # ./gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb:358:in `matches?'

 8/8 |============================================================ 100 =============================================================>| Time: 00:00:04 

Finished in 4.11 seconds (files took 10.41 seconds to load)
8 examples, 1 failure

Failed examples:

rspec ./spec/models/edu_spec.rb:15 # Edu validate validation should only allow numbers for end_year which are less than or equal to 2999

```

But, if I delete the code `greater_than_or_equal_to: :start_year`, it won't raise the error again. 

By the way, it can't support the validation below:

``` ruby
it { is_expected.to validate_numericality_of(:end_year).greater_than_or_equal_to(:start_year)}
```

It will raise the error:

```
NoMethodError:
       undefined method `+' for :start_year:Symbol
     # ./gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/numericality_matchers/comparison_matcher.rb:74:in `block in submatchers'
     # ./gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/numericality_matchers/comparison_matcher.rb:73:in `map'
     #./gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/numericality_matchers/comparison_matcher.rb:73:in `submatchers'
     # ./gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/numericality_matchers/comparison_matcher.rb:82:in `submatchers_and_results'
     # ./gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/numericality_matchers/comparison_matcher.rb:62:in `failing_submatchers'
     # ./gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/numericality_matchers/comparison_matcher.rb:58:in `all_bounds_correct?'
     # ./gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/numericality_matchers/comparison_matcher.rb:34:in `matches?'
     # ./gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb:409:in `block in submatchers_and_results'
     # ./gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb:408:in `map'
     # ./gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb:408:in `submatchers_and_results'
     # ./gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb:414:in `failing_submatchers'
     # ./gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb:358:in `matches?'
     # ./spec/models/edu_spec.rb:13:in `block (4 levels) in <top (required)>'
```

I use rspec, is this not be realized? Or it isn't written in the document?

Thanks.

**Comment by mcmire** [comment]
You're probably getting `comparison of Float with nil failed` because your model is trying to access `start_year` in the process of running the validation and it is nil. So if you give `validate_numericality_of` an instance of Edu where `start_year` is filled in with something then it may work.

Unfortunately, none of the qualifiers on `validate_numericality_of` (`greater_than`, `less_than`, `greater_than_or_equal_to`, etc.) support using a symbol as an argument. It's a newer feature in Rails that hasn't been brought over to shoulda-matchers yet.

**Comment by MDjavaheri** [comment]
@bucket-sven add `if :start_year?` to your first spec example and it'll work.
Just ran into the same issues you mentioned.

**Comment by mcmire** [comment]
Updating the numericality matcher to support a symbol is documented in #688, so I'm closing this in favor of that.
