### ISSUE TITLE
rails 5 depreciation warning validate_uniqueness_of for multiple scopes

### ISSUE THREAD

**Issue by elbartostrikesagain** [thoughtbot/shoulda-matchers#949]
rails: 4.2.6
should-matchers: 3.1.1
(postgres if that matters)

I'm trying to use validate_uniqueness_of for something that is scoped to 2 things(note `default` is a boolean that defaults to false if that matters):

```
validates :default, uniqueness: { scope: [:object_type, :object_id], message: "an addresses object can only have one default" }
```

the test I'm using is:

```
it { should validate_uniqueness_of(:default).scoped_to(:object_type, :object_id).with_message('an addresses object can only have one default')}
```

The test passes but raises a depreciation warning for rails 5 😟 :

```
DEPRECATION WARNING: You attempted to assign a value which is not explicitly `true` or `false` ("an arbitrary value") to a boolean column. Currently this value casts to `false`. This will change to match Ruby's semantics, and will cast to `true` in Rails 5. If you would like to maintain the current behavior, you should explicitly handle the values you would like cast to `false`.)
```

**Comment by s2t2** [comment]
I'm getting a slightly different error:

    it { should validate_uniqueness_of(:first_attribute).scoped_to([:poly_type, :poly_id]) }
     
     NoMethodError:
       undefined method `superclass' for nil:NilClass

Wondering if there is a temporary work-around?

**Comment by mcmire** [comment]
@s2t2 That does seem like a separate issue. Care to post a backtrace?

**Comment by s2t2** [comment]
@mcmire sure, see below:

```` rb
Failures:

  1) Notification validations uniqueness should validate that : first_attribute is case-sensitively unique within the scope of :poly_type and :poly_id
     Failure/Error: it { should validate_uniqueness_of(: first_attribute).scoped_to(:poly_type, :poly_id) }
     
     NoMethodError:
       undefined method `superclass' for nil:NilClass
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-5.0.3/lib/active_record/validations/uniqueness.rb:47:in `find_finder_class_for'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-5.0.3/lib/active_record/validations/uniqueness.rb:14:in `validate_each'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activemodel-5.0.3/lib/active_model/validator.rb:151:in `block in validate'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activemodel-5.0.3/lib/active_model/validator.rb:148:in `each'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activemodel-5.0.3/lib/active_model/validator.rb:148:in `validate'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:405:in `public_send'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:405:in `block in make_lambda'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:169:in `call'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:547:in `call'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:547:in `block (2 levels) in default_terminator'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:546:in `catch'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:546:in `block in default_terminator'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:170:in `call'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:170:in `block in halting'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:454:in `call'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:454:in `block in call'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:454:in `each'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:454:in `call'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:750:in `_run_validate_callbacks'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activemodel-5.0.3/lib/active_model/validations.rb:408:in `run_validations!'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activemodel-5.0.3/lib/active_model/validations/callbacks.rb:113:in `block in run_validations!'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:126:in `call'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:126:in `call'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:455:in `call'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:455:in `call'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:750:in `_run_validation_callbacks'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activemodel-5.0.3/lib/active_model/validations/callbacks.rb:113:in `run_validations!'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activemodel-5.0.3/lib/active_model/validations.rb:338:in `valid?'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-5.0.3/lib/active_record/validations.rb:65:in `valid?'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-5.0.3/lib/active_record/validations/associated.rb:13:in `valid_object?'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-5.0.3/lib/active_record/validations/associated.rb:5:in `block in validate_each'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-5.0.3/lib/active_record/validations/associated.rb:5:in `reject'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-5.0.3/lib/active_record/validations/associated.rb:5:in `validate_each'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activemodel-5.0.3/lib/active_model/validator.rb:151:in `block in validate'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activemodel-5.0.3/lib/active_model/validator.rb:148:in `each'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activemodel-5.0.3/lib/active_model/validator.rb:148:in `validate'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:405:in `public_send'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:405:in `block in make_lambda'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:169:in `call'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:547:in `call'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:547:in `block (2 levels) in default_terminator'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:546:in `catch'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:546:in `block in default_terminator'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:170:in `call'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:170:in `block in halting'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:454:in `call'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:454:in `block in call'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:454:in `each'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:454:in `call'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:750:in `_run_validate_callbacks'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activemodel-5.0.3/lib/active_model/validations.rb:408:in `run_validations!'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activemodel-5.0.3/lib/active_model/validations/callbacks.rb:113:in `block in run_validations!'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:126:in `call'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:126:in `call'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:455:in `call'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:455:in `call'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:750:in `_run_validation_callbacks'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activemodel-5.0.3/lib/active_model/validations/callbacks.rb:113:in `run_validations!'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activemodel-5.0.3/lib/active_model/validations.rb:338:in `valid?'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-5.0.3/lib/active_record/validations.rb:65:in `valid?'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validator.rb:96:in `perform_validation'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validator.rb:89:in `validation_result'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validator.rb:85:in `validation_error_messages'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validator.rb:64:in `messages'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validator.rb:25:in `has_messages?'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validator.rb:55:in `messages_match?'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validator.rb:21:in `call'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:38:in `matches?'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:42:in `does_not_match?'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:28:in `each'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:28:in `detect'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:28:in `first_failing'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher.rb:533:in `public_send'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher.rb:533:in `run'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher.rb:394:in `matches?'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validation_matcher.rb:155:in `run_allow_or_disallow_matcher'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validation_matcher.rb:88:in `allows_value_of'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb:660:in `block in validate_after_scope_change?'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb:648:in `each'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb:648:in `all?'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb:648:in `validate_after_scope_change?'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb:332:in `matches?'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-expectations-3.5.0/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-expectations-3.5.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-expectations-3.5.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/memoized_helpers.rb:81:in `should'
     # ./spec/models/notification_spec.rb:24:in `block (4 levels) in <top (required)>'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:254:in `instance_exec'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:254:in `block in run'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:496:in `block in with_around_and_singleton_context_hooks'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:453:in `block in with_around_example_hooks'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/hooks.rb:464:in `block in run'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/hooks.rb:604:in `block in run_around_example_hooks_for'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:338:in `call'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:338:in `call'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-rails-3.5.2/lib/rspec/rails/adapters.rb:127:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:443:in `instance_exec'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:443:in `instance_exec'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/hooks.rb:375:in `execute_with'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/hooks.rb:606:in `block (2 levels) in run_around_example_hooks_for'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:338:in `call'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:338:in `call'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/hooks.rb:607:in `run_around_example_hooks_for'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/hooks.rb:464:in `run'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:453:in `with_around_example_hooks'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:496:in `with_around_and_singleton_context_hooks'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:251:in `run'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:627:in `block in run_examples'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:623:in `map'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:623:in `run_examples'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:589:in `run'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:590:in `block in run'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:590:in `map'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:590:in `run'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:590:in `block in run'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:590:in `map'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:590:in `run'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:113:in `block (3 levels) in run_specs'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:113:in `map'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:113:in `block (2 levels) in run_specs'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1835:in `with_suite_hooks'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:112:in `block in run_specs'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:77:in `report'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:111:in `run_specs'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:87:in `run'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
     # /usr/local/var/rbenv/versions/2.2.3/bin/rspec:23:in `load'
     # /usr/local/var/rbenv/versions/2.2.3/bin/rspec:23:in `<top (required)>'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
     # /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
     # /usr/local/var/rbenv/versions/2.2.3/bin/bundle:23:in `load'
     # /usr/local/var/rbenv/versions/2.2.3/bin/bundle:23:in `<main>'
````

**Comment by mcmire** [comment]
Sorry for the delay on this. I've just created #1073 to fix the OP's issue. (The second issue reported here, I haven't investigated yet, but I don't think it's related.)
