### ISSUE TITLE
Rails 5.0.0, Get `undefined method `configure' for Shoulda::Matchers:Module' error.

### ISSUE THREAD

**Issue by zw963** [thoughtbot/shoulda-matchers#953]
Rails 5.0.0, config with following process:
1.  Add following config to Gemfile

``` ruby
group :test do
  gem 'shoulda', '~> 3.5'
  gem 'shoulda-matchers'
end
```
1.  run  bundle install
2.  Add following code to test/test_helper

``` ruby
Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    with.test_framework :minitest
    with.library :rails
  end
end
```
1. Run rake test. Got

``` sh
rake aborted!
NoMethodError: undefined method `configure' for Shoulda::Matchers:Module
/home/zw963/Xthink/ershou_web/test/test_helper.rb:20:in `<top (required)>'
```

Thanks

**Comment by mcmire** [comment]
`shoulda` still brings in `shoulda-matchers` 2.x, it doesn't bring in 3.x yet. So you don't need the `configure` block.

More info: <https://github.com/thoughtbot/shoulda-matchers#minitest>

**Comment by zw963** [comment]
Thanks for reply, I tried the example in README for minitest with add same configure to test/test-helper, it not worked, So I create issue here.


If without configure, will get another error..
e.g. 

```rb
class Api::V1::TestControllerTest < ActionDispatch::IntegrationTest
   should route(:get, '/test/v1/hello').to('test#hello')
end
```

Get following error:

```rb
NoMethodError: undefined method `route' for Api::V1::TestControllerTest:Class
```

**Comment by zw963** [comment]
this file location is: ``/Project/test/controllers/api/v1/test_controller_test.rb``

**Comment by zw963** [comment]
Sorry, Is there exist a clean guide for minitest worked with shoulda-matcher?

I use matchers for years, but just with Rspec, it basically no problem.
now, I swtich to rails default minitest,  with config or without config, 
could not make `should` or `route` worked for me.

If i need use `shoulda-context` gems?

**Comment by zw963** [comment]
I notice following code PersonTest is inhered from `ActiveSupport::TestCase`

```rb
class PersonTest < ActiveSupport::TestCase
  should validate_presence_of(:name)
end
```

Current, my code is inhered from `ActionDispatch::IntegrationTest`

Which is default generated code by rails 5.

**Comment by zw963** [comment]
Any advice ? 

Thanks.

**Comment by mcmire** [comment]
Okay, that's definitely a bug. It looks like [here](https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/integrations/libraries/routing.rb#L15) we need to not only include the routing matchers into ActionController::TestCase but also ActionDispatch::IntegrationTest.

You can fix this in the meantime by adding this to the top of your test class:

```
include Shoulda::Matchers::Routing
```

**Comment by zw963** [comment]
Hi, I have tried with following:

1. add following into gemfile
```rb
group :test do
  gem 'shoulda', '~> 3.5'
  gem 'shoulda-matchers', '~> 2.0'
end
```

2.  run `bundle install`

3.  add test to `Project/test/integration/routes_test.rb`
```rb
require 'test_helper'
class Api::V1::TestControllerTest < ActionDispatch::IntegrationTest
  include Shoulda::Matchers::Routing
    test 'api route' do
      should route(:get, '/v1/test/hello').to('api/v1/test#hello')
    end
end
```

4. Get following error


`uninitialized constant Shoulda::Matchers::Routing`

Thanks

**Comment by zw963** [comment]
I notice route method should be:

```Shoulda::Matchers::ActionController#route```

I have confused about which version should-matcher I need to use??

**Comment by zw963** [comment]
```rb
class RoutesTest < ActionController::TestCase

should route(:get, 'v1/test/hello').to('api/v1/test#hello')
```

This still worked for rails 5.0.0.

**Comment by zw963** [comment]
Following not worked for me neigher 2.x or 3.x.

```rb
class RoutesTest < ActionDispatch::IntegrationTest
  include Shoulda::Matchers::Routing
end
```

```rb
class RoutesTest < ActionDispatch::IntegrationTest
  include Shoulda::Matchers::ActionController
end
```

**Comment by mcmire** [comment]
Oh, I forgot I moved the `route` matcher to a separate module in shoulda-matchers 3. In 2.x, it was still located in Shoulda::Matchers::ActionController.

Are you sure this doesn't work in 2.x?

``` ruby
class RoutesTest < ActionDispatch::IntegrationTest
  include Shoulda::Matchers::ActionController

  should route(...)
end
```

**Comment by zw963** [comment]
I try again,

Hi, I have tried with following:

1. add following into gemfile
```rb
group :test do
  gem 'shoulda', '~> 3.5'
  gem 'shoulda-matchers', '~> 2.0'
end
```

2.  run `bundle install`

3.  add test to `Project/test/integration/routes_test.rb`
```rb
require 'test_helper'
class RoutesTest < ActionDispatch::IntegrationTest
  include Shoulda::Matchers::ActionController

  should route(:get, 'v1/test/hello').to('api/v1/test#hello')
end
```

4. Get following error

NoMethodError: undefined method `route' for RoutesTest:Class

Thanks

**Comment by mcmire** [comment]
Oops! I forgot that using `shoulda`, the matchers are defined as class methods, not instance methods. Try:

``` ruby
require 'test_helper'
class RoutesTest < ActionDispatch::IntegrationTest
  # note: 'extend', not 'include'
  extend Shoulda::Matchers::ActionController

  should route(:get, 'v1/test/hello').to('api/v1/test#hello')
end
```

**Comment by zw963** [comment]
Not.

```NameError: uninitialized constant Routes```

**Comment by mcmire** [comment]
Backtrace, please?

**Comment by zw963** [comment]
```sh
rake aborted!
NameError: uninitialized constant Api
/home/zw963/Xthink/ershou_web/test/controllers/api/v1/apply_logs_controller_test.rb:1:in `<top (required)>'
/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/railties-5.0.0/lib/rails/test_unit/test_requirer.rb:11:in `block in require_files'
/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/railties-5.0.0/lib/rails/test_unit/test_requirer.rb:10:in `each'
/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/railties-5.0.0/lib/rails/test_unit/test_requirer.rb:10:in `require_files'
/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/railties-5.0.0/lib/rails/test_unit/minitest_plugin.rb:76:in `plugin_rails_init'
/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/minitest-5.9.0/lib/minitest.rb:80:in `block in init_plugins'
/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/minitest-5.9.0/lib/minitest.rb:78:in `each'
/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/minitest-5.9.0/lib/minitest.rb:78:in `init_plugins'
/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/minitest-5.9.0/lib/minitest.rb:129:in `run'
/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/railties-5.0.0/lib/rails/test_unit/minitest_plugin.rb:64:in `rake_run'
/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/railties-5.0.0/lib/rails/test_unit/testing.rake:15:in `block in <top (required)>'
/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/rake-11.2.2/lib/rake/task.rb:248:in `call'
/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/rake-11.2.2/lib/rake/task.rb:248:in `block in execute'
/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/rake-11.2.2/lib/rake/task.rb:243:in `each'
/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/rake-11.2.2/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/home/zw963/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/rake-11.2.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/rake-11.2.2/lib/rake/task.rb:173:in `invoke'
/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/rake-11.2.2/lib/rake/application.rb:152:in `invoke_task'
/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/rake-11.2.2/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/rake-11.2.2/lib/rake/application.rb:108:in `each'
/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/rake-11.2.2/lib/rake/application.rb:108:in `block in top_level'
/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/rake-11.2.2/lib/rake/application.rb:117:in `run_with_threads'
/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/rake-11.2.2/lib/rake/application.rb:102:in `top_level'
/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/rake-11.2.2/lib/rake/application.rb:80:in `block in run'
/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/rake-11.2.2/lib/rake/application.rb:77:in `run'
/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/bin/rake:23:in `load'
/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/bin/rake:23:in `<main>'
/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/bin/ruby_executable_hooks:15:in `eval'
/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by mcmire** [comment]
Is that constant really defined?

**Comment by zw963** [comment]
Yes, as you can see, `Api` is a controller module name, which auto create by rails framework.

I prefer create a new controller like this:

```rb
class Api::V1::CommentsController < Api::V1::BaseController
   ....
end
```

Not like this.

```rb
module Api
  module V1
    CommentsController < Api::V1::BaseController
       ...
    end
  end
end
```

**Comment by mcmire** [comment]
I'm closing this due to lack of activity. If this is still an issue, please respond and I will take another look. Thanks!

**Comment by zw963** [comment]
Sorry, to long ago ... never remember why my this issue talk about ... : (

**Comment by febeling** [comment]
I still have this same problem.

**Comment by ericchapman** [comment]
Make sure you have the following somewhere in your Rails application

``` ruby
Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    with.test_framework :rspec
    with.library :rails
  end
end
```

I have it in my "spec/rails_helper.rb" file so it only runs if I am running tests

**Comment by delacruzjames** [comment]
Same issue here. rails 6.0.2.2

`undefined method `configure' for Shoulda::Matchers:Module`

**Comment by delacruzjames** [comment]
@mcmire 

RSpec.configure do |config|
  config.include(Shoulda::Matchers::ActiveModel, type: :model)
  config.include(Shoulda::Matchers::ActiveRecord, type: :model)
end

It works on my end when I added ShouldaMatcher inside RSpec.configure

**Comment by mcmire** [comment]
@delacruzjames Which version of shoulda-matchers are you using?

**Comment by delacruzjames** [comment]
@mcmire 
* shoulda-matchers (3.1.3)
	Summary: Making tests easy on the fingers and eyes
	Homepage: http://thoughtbot.com/community/
	Path: /Users/jamesdelacruz/.rvm/gems/ruby-2.6.5/gems/shoulda-matchers-3.1.3

**Comment by delacruzjames** [comment]
@mcmire BTW I tried to get the latest version of shoulda-matchers 4.3.0 and it looks fine on my end.

**Comment by mcmire** [comment]
@delacruzjames Yeah, that's what I would have recommended. :) Glad that worked for you!
